import { test, expect } from '../fixtures/test'
import { importBundle, openChatInput } from '../fixtures/import'

test('chat restore applies after confirmation and remains recoverable after reload', async ({ page }, testInfo) => {
  await importBundle(page)
  const toast = page.getByRole('button', { name: 'Close toast', exact: true }).first()
  if (await toast.isVisible()) await toast.click()
  await openChatInput(page)
  await page.getByRole('button', { name: '管理範本', exact: true }).click()
  const manager = page.getByRole('dialog', { name: '管理聊天模板', exact: true })
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 })
    await manager.getByRole('button', { name: '還原系統範本', exact: true }).scrollIntoViewIfNeeded()
    await manager.screenshot({ path: testInfo.outputPath(`restore-location-${width}.png`), animations: 'disabled' })
  }
  await page.setViewportSize({ width: 1440, height: 900 })
  const original = '請保留我的自訂 prompt — 測試復原 123'
  await manager.locator('textarea').fill(original)
  await manager.getByRole('button', { name: '還原系統範本', exact: true }).click()
  await expect(page.getByRole('button', { name: '保留目前內容' })).toBeFocused()
  await page.getByRole('button', { name: '保留目前內容' }).click()
  await expect(manager.locator('textarea')).toHaveValue(original)
  await expect(manager.getByRole('button', { name: '還原系統範本', exact: true })).toBeFocused()
  await manager.getByRole('button', { name: '還原系統範本', exact: true }).click()
  const confirmation = page.getByRole('alertdialog')
  for (const [width, height] of [[320,900],[390,900],[430,900],[768,900],[1024,900],[1440,900],[844,390]]) {
    await page.setViewportSize({ width, height })
    expect(await confirmation.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
    await confirmation.screenshot({ path: testInfo.outputPath(`restore-confirmation-${width}.png`), animations: 'disabled' })
  }
  await confirmation.getByRole('button', { name: '還原系統範本', exact: true }).click()
  await expect(confirmation).toBeHidden()
  await expect(manager.getByRole('button', { name: '找回還原前的版本' })).toBeVisible()
  await expect(page.getByRole('dialog', { name: '範本編輯預覽', exact: true })).toHaveCount(0)
  await expect(manager.locator('textarea')).not.toHaveValue(original)
  await expect(page.locator('[data-sonner-toast]').filter({ hasText: '已還原系統範本。' })).toBeVisible()
  await manager.screenshot({ path: testInfo.outputPath('restore-notification.png'), animations: 'disabled' })
  await page.reload()
  await openChatInput(page)
  await page.getByRole('button', { name: '管理範本', exact: true }).click()
  await manager.getByRole('button', { name: '找回還原前的版本' }).click()
  await expect(manager.locator('textarea')).toHaveValue(original)
  await expect(page.locator('[data-sonner-toast]').filter({ hasText: '已找回還原前的版本。' })).toBeVisible()
  await expect(manager.getByText('已找回還原前的版本。', { exact: true })).toHaveCount(0)
  await expect(manager.getByRole('button', { name: '找回還原前的版本' })).toHaveCount(0)
})

test('custom summary restores directly and recovers complete module content', async ({ page }) => {
  await importBundle(page)
  await page.getByRole('tab', { name: '醫療摘要', exact: true }).click()
  await page.getByRole('tab', { name: '自訂摘要', exact: true }).click()
  await page.getByRole('button', { name: '管理模組', exact: true }).click()
  const manager = page.getByRole('dialog').filter({ has: page.getByRole('button', { name: '還原系統範本', exact: true }) })
  await manager.locator('textarea').first().fill('我的摘要 prompt')
  const continueGuest = page.getByRole('button', { name: '暫不登入，只在本頁使用' })
  if (await continueGuest.isVisible()) await continueGuest.click()
  await manager.locator('textarea').first().fill('我的摘要 prompt')
  await manager.getByRole('button', { name: '還原系統範本', exact: true }).click()
  const confirmation = page.getByRole('alertdialog')
  await confirmation.getByRole('button', { name: '還原系統範本', exact: true }).click()
  await expect(confirmation).toBeHidden()
  await expect(manager.getByRole('button', { name: '找回還原前的版本' })).toBeVisible()
  await expect(manager.locator('textarea').first()).not.toHaveValue('我的摘要 prompt')
  await manager.getByRole('button', { name: '找回還原前的版本' }).click()
  await expect(manager.locator('textarea').first()).toHaveValue('我的摘要 prompt')
  await expect(manager.getByRole('button', { name: '找回還原前的版本' })).toHaveCount(0)
})
