import type { NextConfig } from "next";
import path from "path";

const isGhPages = process.env.GITHUB_PAGES === "true";

// Optional second static-export target: the official mirror at
// mediprisma.tw/app. Set DEPLOY_BASE_PATH=/app to build that artifact.
// Any non-empty value turns on the same static export + basePath wiring
// that GitHub Pages uses, just under a different subpath.
const deployBasePath = process.env.DEPLOY_BASE_PATH || "";
const isStaticExport = isGhPages || deployBasePath !== "";

const basePath = deployBasePath
  ? deployBasePath
  : isGhPages
    ? "/medical-note-smart-on-fhir"
    : "";

// Detect when running inside a Claude Code worktree
// (e.g. .claude/worktrees/<branch>/). Worktrees don't have their own
// node_modules, so Turbopack needs to be pointed at the main project root.
const isWorktree = __dirname.includes('.claude/worktrees/');
const projectRoot = isWorktree ? path.join(__dirname, '../../..') : __dirname;

const nextConfig: NextConfig = {
  // Static export is only required for the GitHub Pages deploy. In dev mode
  // (and on Vercel) we want the full Next.js server so dynamic API routes
  // like /api/feedback work. Without this gate, `output: "export"` forces
  // every route to be statically renderable, which breaks API routes.
  ...(isStaticExport ? { output: "export" as const } : {}),
  images: { unoptimized: true },
  // 避免 Next 往上層亂抓 lockfile（雲端同步/家目錄）
  // worktree mode: point at main project where node_modules lives
  outputFileTracingRoot: projectRoot,
  ...(isWorktree
    ? {
        turbopack: {
          root: projectRoot,
        },
      }
    : {}),
  // Static-export targets (GH Pages, mediprisma /app) need basePath / assetPrefix
  ...(isStaticExport
    ? {
        basePath: basePath,
        assetPrefix: `${basePath}/`,
        trailingSlash: false, // 建議 false
      }
    : {
        trailingSlash: false,
      }),
  // 暴露 basePath 給客戶端
  env: {
    NEXT_PUBLIC_BASE_PATH: basePath,
    // App version is no longer baked in here — VersionLink fetches it from
    // /version.json at runtime (regenerated by scripts/write-version.mjs on
    // every `npm version` bump). Build-time inlining cached the version in
    // the client bundle and forced a dev-server restart after each bump.
  },
  // Security headers (CSP disabled for local development).
  //
  // X-Frame-Options dropped on purpose: its only "allow-list" value is
  // ALLOW-FROM which Chrome ignores, so the SAMEORIGIN default blocks the
  // EHR-FHIR Bridge extension from embedding this app inside HIS pages
  // (NHI 健保存摺, vghtpe). We rely on CSP frame-ancestors instead —
  // modern browsers honour CSP over the legacy header. Restrict to a
  // whitelist of trusted HIS hosts (plus 'self' so the app's own
  // /smart/launch flow keeps working).
  //
  // Note: this only affects `next dev` / `next start`. GH Pages serves
  // static files via GitHub's CDN where headers() has no effect.
  async headers() {
    return [
      {
        source: '/:path*',
        headers: [
          {
            key: 'Content-Security-Policy',
            value:
              "frame-ancestors 'self' " +
              "https://myhealthbank.nhi.gov.tw " +
              "https://*.vghtpe.gov.tw " +
              "http://localhost:5001"  // mock-his
          },
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'X-XSS-Protection', value: '1; mode=block' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'Permissions-Policy', value: 'camera=(), microphone=(self), geolocation=()' }
        ]
      }
    ]
  },
};

export default nextConfig;
