// Refactored Clinical Insights Settings
"use client"

import { Button } from "@/components/ui/button"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import { useLanguage } from "@/src/application/providers/language.provider"
import { useClinicalInsightsConfig } from "@/src/application/providers/clinical-insights-config.provider"
import { InsightTabEditor } from './InsightTabEditor'

export function ClinicalInsightsSettings() {
  const { t } = useLanguage()
  const { 
    panels, 
    updatePanel, 
    addPanel, 
    removePanel, 
    resetPanels, 
    maxPanels, 
    reorderPanels, 
    autoGenerate, 
    setAutoGenerate 
  } = useClinicalInsightsConfig()

  const canAddPanel = panels.length < maxPanels
  const canRemovePanel = panels.length > 1

  const handleMove = (panelId: string, direction: "up" | "down") => {
    const currentIndex = panels.findIndex((panel) => panel.id === panelId)
    if (currentIndex === -1) return

    const targetIndex = direction === "up" ? currentIndex - 1 : currentIndex + 1
    if (targetIndex < 0 || targetIndex >= panels.length) return

    const orderIds = [...panels.map((panel) => panel.id)]
    const [removed] = orderIds.splice(currentIndex, 1)
    orderIds.splice(targetIndex, 0, removed)
    reorderPanels(orderIds)
  }

  return (
    <div className="space-y-5">
      <div className="space-y-1">
        <h3 className="text-base font-semibold leading-tight">{t.settings.clinicalInsightsSettingsTitle}</h3>
        <p className="text-xs text-muted-foreground">
          {t.settings.clinicalInsightsSettingsDesc}
        </p>
      </div>

      <div className="space-y-5">
        {/* Auto-generate Toggle */}
        <div className="flex items-center space-x-2 rounded-lg border p-4">
          <Checkbox
            id="auto-generate"
            checked={autoGenerate}
            onCheckedChange={(checked) => setAutoGenerate(checked as boolean)}
          />
          <div className="grid gap-1.5 leading-none">
            <Label
              htmlFor="auto-generate"
              className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
            >
              {t.settings.autoGenerateInsights}
            </Label>
            <p className="text-xs text-muted-foreground">
              {t.settings.autoGenerateDesc}
            </p>
          </div>
        </div>

        {/* Insight Tabs */}
        {panels.map((panel, index) => (
          <InsightTabEditor
            key={panel.id}
            panel={panel}
            index={index}
            canRemove={canRemovePanel}
            canMoveUp={index > 0}
            canMoveDown={index < panels.length - 1}
            onUpdate={updatePanel}
            onRemove={removePanel}
            onMove={handleMove}
          />
        ))}

        {/* Actions */}
        <div className="flex flex-wrap items-center gap-3">
          <Button type="button" onClick={addPanel} disabled={!canAddPanel}>
            {t.settings.addTab}
          </Button>
          <Button type="button" variant="ghost" onClick={resetPanels}>
            {t.settings.resetToDefaults}
          </Button>
          <span className="text-xs text-muted-foreground">
            {panels.length}/{maxPanels} {t.settings.tabsInUse}
          </span>
        </div>
      </div>
    </div>
  )
}

export default ClinicalInsightsSettings
