// Insight Tab Editor Component
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Checkbox } from "@/components/ui/checkbox"
import { Label } from "@/components/ui/label"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip"
import { Info } from "lucide-react"
import { useLanguage } from "@/src/application/providers/language.provider"

interface InsightPanel {
  id: string
  title: string
  prompt: string
  autoGenerate: boolean
}

interface InsightTabEditorProps {
  panel: InsightPanel
  index: number
  canRemove: boolean
  canMoveUp: boolean
  canMoveDown: boolean
  onUpdate: (id: string, updates: Partial<InsightPanel>) => void
  onRemove: (id: string) => void
  onMove: (id: string, direction: "up" | "down") => void
}

export function InsightTabEditor({
  panel,
  index,
  canRemove,
  canMoveUp,
  canMoveDown,
  onUpdate,
  onRemove,
  onMove,
}: InsightTabEditorProps) {
  const { t } = useLanguage()
  
  return (
    <div className="space-y-3 rounded-lg border p-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div className="flex-1 space-y-1">
          <div className="flex items-center justify-between">
            <p className="text-sm font-semibold">{t.settings.tab} {index + 1}</p>
            {canRemove && (
              <Button
                type="button"
                variant="outline"
                size="sm"
                onClick={() => onRemove(panel.id)}
                className="border-2 border-destructive/50 text-destructive hover:border-destructive hover:bg-destructive/10"
              >
                {t.settings.remove}
              </Button>
            )}
          </div>
          <div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground">
            <span className="font-medium text-foreground">{t.settings.orderControls}</span>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onMove(panel.id, "up")}
              disabled={!canMoveUp}
              aria-label={`Move tab ${index + 1} up`}
            >
              {t.settings.moveUp}
            </Button>
            <Button
              type="button"
              variant="outline"
              size="sm"
              onClick={() => onMove(panel.id, "down")}
              disabled={!canMoveDown}
              aria-label={`Move tab ${index + 1} down`}
            >
              {t.settings.moveDown}
            </Button>
            <div className="flex items-center space-x-1 ml-2">
              <Checkbox
                id={`auto-generate-${panel.id}`}
                checked={panel.autoGenerate}
                onCheckedChange={(checked) => onUpdate(panel.id, { autoGenerate: checked as boolean })}
                className="border-2 border-primary/60 data-[state=checked]:bg-primary data-[state=checked]:border-primary"
              />
              <Label
                htmlFor={`auto-generate-${panel.id}`}
                className="text-xs font-medium cursor-pointer"
              >
                {t.settings.autoGenerateInsights}
              </Label>
              <TooltipProvider delayDuration={200}>
                <Tooltip>
                  <TooltipTrigger asChild>
                    <Info className="h-3.5 w-3.5 text-muted-foreground cursor-help" />
                  </TooltipTrigger>
                  <TooltipContent side="right" className="max-w-sm">
                    <p className="text-xs">
                      {t.settings.autoGenerateDesc}
                    </p>
                  </TooltipContent>
                </Tooltip>
              </TooltipProvider>
            </div>
          </div>
        </div>
      </div>

      <div className="grid gap-3">
        <div className="grid gap-1.5">
          <label className="text-xs font-medium uppercase text-muted-foreground">{t.settings.tabLabel}</label>
          <Input
            value={panel.title}
            onChange={(event) => onUpdate(panel.id, { title: event.target.value })}
            placeholder={t.settings.tabLabelPlaceholder}
          />
        </div>

        <div className="grid gap-1.5">
          <label className="text-xs font-medium uppercase text-muted-foreground">{t.settings.prompt}</label>
          <Textarea
            value={panel.prompt}
            onChange={(event) => onUpdate(panel.id, { prompt: event.target.value })}
            className="min-h-[70px] resize-vertical text-sm"
            placeholder={t.settings.promptPlaceholderInsight}
          />
        </div>
      </div>
    </div>
  )
}
