import { render, screen } from "@testing-library/react"
import { SummaryStatusStrip } from "@/features/medical-summary/components/SummaryStatusStrip"
import { buildSummaryGenerationInfo } from "@/features/medical-summary/utils/summary-generation-info"

const COVERAGE = {
  organizations: 3,
  encounters: 12,
  medications: 20,
  labs: 8,
  procedures: 2,
}

const LABELS = {
  orgs: "{count} 家院所",
  encounters: "{count} 次就診",
  medications: "{count} 筆用藥",
  labs: "{count} 份檢驗",
}

function normalizeWhitespace(value: string): string {
  return value.replace(/\s+/gu, " ")
}

const generationInfo = (locale: "zh-TW" | "en") => buildSummaryGenerationInfo({
  generation: {
    source: "live",
    modelId: "openai-compatible-custom",
    modelName: "tvghbrain3.5",
    generatedAt: new Date("2026-09-06T02:00:00.000Z").getTime(),
    completedAt: new Date("2026-09-06T02:00:41.000Z").getTime(),
    firstCardMs: 12_000,
    durationMs: 41_000,
  },
  locale,
  ...(locale === "zh-TW"
    ? {
      labelTemplate: "由 {model} 於 {time} 產生",
      labelWithDurationTemplate: "由 {model} 於 {time} 產生，總耗時 {duration}",
      labelWithFirstCardTemplate: "由 {model} 於 {time} 產生，首段 {first}，總耗時 {duration}",
      generatedAtLabel: "產生時間：",
      durationLabel: "耗時",
      firstCardLabel: "首段",
      preGeneratedLabel: "預產生",
      preGeneratedTemplate: "預產生摘要，由 {model} 建立",
    }
    : {
      labelTemplate: "Generated by {model} at {time}",
      labelWithDurationTemplate: "Generated by {model} at {time}; total time {duration}",
      labelWithFirstCardTemplate:
        "Generated by {model} at {time}; first section {first}, total time {duration}",
      generatedAtLabel: "Generated at: ",
      durationLabel: "Time",
      firstCardLabel: "First section",
      preGeneratedLabel: "Pre-generated",
      preGeneratedTemplate: "Pre-generated summary created with {model}",
    }),
})

describe("SummaryStatusStrip generation meta", () => {
  it("shows 首段 and 耗時 side by side", () => {
    render(
      <SummaryStatusStrip
        coverage={COVERAGE}
        statsVisible
        labels={LABELS}
        generationInfo={generationInfo("zh-TW")}
        runningLabel="產生中"
        runningAriaTemplate="正在使用 {model} 產生摘要，已進行 {elapsed}"
      />,
    )
    const meta = screen.getByTestId("medical-summary-generation-meta")
    expect(normalizeWhitespace(meta.textContent ?? "")).toContain("首段 00:12")
    expect(normalizeWhitespace(meta.textContent ?? "")).toContain("耗時 00:41")
    expect(meta.getAttribute("aria-label")).toContain("首段 00:12")
    expect(meta.getAttribute("aria-label")).toContain("總耗時 00:41")
  })

  it("shows the English first-section label", () => {
    render(
      <SummaryStatusStrip
        coverage={COVERAGE}
        statsVisible
        labels={LABELS}
        generationInfo={generationInfo("en")}
        runningLabel="Generating"
        runningAriaTemplate="Generating the summary with {model}; elapsed {elapsed}"
      />,
    )
    const meta = screen.getByTestId("medical-summary-generation-meta")
    expect(normalizeWhitespace(meta.textContent ?? "")).toContain("First section 00:12")
    expect(normalizeWhitespace(meta.textContent ?? "")).toContain("Time 00:41")
  })

  it("omits the first-section timing for a legacy result that never measured it", () => {
    const info = buildSummaryGenerationInfo({
      generation: {
        source: "live",
        modelId: "openai-compatible-custom",
        modelName: "tvghbrain3.5",
        generatedAt: new Date("2026-09-06T02:00:00.000Z").getTime(),
        completedAt: new Date("2026-09-06T02:00:41.000Z").getTime(),
        durationMs: 41_000,
      },
      locale: "zh-TW",
      labelTemplate: "由 {model} 於 {time} 產生",
      labelWithDurationTemplate: "由 {model} 於 {time} 產生，總耗時 {duration}",
      labelWithFirstCardTemplate: "由 {model} 於 {time} 產生，首段 {first}，總耗時 {duration}",
      generatedAtLabel: "產生時間：",
      durationLabel: "耗時",
      firstCardLabel: "首段",
      preGeneratedLabel: "預產生",
      preGeneratedTemplate: "預產生摘要，由 {model} 建立",
    })
    render(
      <SummaryStatusStrip
        coverage={COVERAGE}
        statsVisible
        labels={LABELS}
        generationInfo={info}
        runningLabel="產生中"
        runningAriaTemplate="正在使用 {model} 產生摘要，已進行 {elapsed}"
      />,
    )
    const meta = screen.getByTestId("medical-summary-generation-meta")
    expect(normalizeWhitespace(meta.textContent ?? "")).not.toContain("首段")
    expect(normalizeWhitespace(meta.textContent ?? "")).toContain("耗時 00:41")
  })
})
