// Clinical Insights Types
import type { AiQueryResponse } from "@/src/core/entities/ai.entity"
import type {
  InsightLanguagePolicy,
  InsightOutputFormat,
} from "@/src/shared/constants/clinical-insights.constants"

export type QueryMetadata = AiQueryResponse['metadata']

export interface InsightGenerationMetadata extends QueryMetadata {
  /** Live generation or a bundled, audited demo snapshot. Legacy entries may omit it. */
  source?: 'live' | 'pre-generated'
  /** Human-readable model identity captured at generation time. */
  modelName?: string
  /** Wall-clock completion time in epoch milliseconds. */
  generatedAt?: number
  /** Model request duration in milliseconds (queue time excluded). */
  durationMs?: number
  /** Output contract used for these exact generated bytes. */
  outputFormat?: InsightOutputFormat
  /** Language contract used for this generation. */
  languagePolicy?: InsightLanguagePolicy
}

export interface ActiveInsightGeneration {
  id: string
  modelName: string
  startedAt: number
}

export interface PanelStatus {
  isLoading: boolean
  error: Error | null
  activeGeneration?: ActiveInsightGeneration
}

export interface ResponseEntry {
  text: string
  isEdited: boolean
  metadata: InsightGenerationMetadata | null
}

export interface InsightPanelProps {
  panelId: string
  title: string
  subtitle?: string
  prompt: string
  onPromptChange: (value: string) => void
  onRegenerate: () => void
  onStopGeneration: () => void
  isLoading: boolean
  response: string
  error: Error | null
  canGenerate: boolean
  hasData: boolean
  onResponseChange: (value: string) => void
  onClearResponse: () => void
  isEdited: boolean
  modelMetadata: InsightGenerationMetadata | null
  autoGenerate?: boolean
  /** Toggle this panel's auto-generate-on-load setting (persists per config). */
  onToggleAutoGenerate?: (value: boolean) => void
  isEditMode?: boolean
}
