"use client"

import { createContext, useCallback, useContext, useEffect, useMemo, useRef, useState, type ReactNode } from "react"
import { useLanguage } from "./language.provider"
import { useAudience, type Audience } from "./audience.provider"
import { useAuth } from "@/src/application/providers/auth.provider"
import {
  applyClinicalInsightPanelChanges,
  subscribeToClinicalInsightPanels,
} from "@/src/infrastructure/firebase/clinical-insights-sync"
import { stripLegacySafetyPanels } from "./clinical-insights-legacy"
import {
  coerceInsightLanguagePolicy,
  coerceInsightOutputFormat,
  MAX_AUTO_INSIGHT_MODULES,
  MAX_SUMMARY_INSIGHT_MODULES,
  type InsightLanguagePolicy,
  type InsightOutputFormat,
} from "@/src/shared/constants/clinical-insights.constants"

export { MAX_AUTO_INSIGHT_MODULES, MAX_SUMMARY_INSIGHT_MODULES }

export type InsightPanelConfig = {
  id: string
  title: string
  prompt: string
  /** Whether this template is an active module rendered in Medical Summary. */
  showInSummary: boolean
  autoGenerate: boolean
  order: number
  audience: Audience
  /** Tracks one-time additions to the bundled template library. */
  templateLibraryRevision?: number
  /** How the generated bytes should be interpreted by the result renderer. */
  outputFormat: InsightOutputFormat
  /** Whether the model follows the template's language or the interface locale. */
  languagePolicy: InsightLanguagePolicy
}

export const CLINICAL_INSIGHT_TEMPLATE_LIBRARY_REVISION = 1

type BundledInsightPanelConfig = Omit<InsightPanelConfig, "audience" | "outputFormat" | "languagePolicy">
  & Partial<Pick<InsightPanelConfig, "outputFormat" | "languagePolicy">>

const DEFAULT_PANELS_EN_MEDICAL: BundledInsightPanelConfig[] = [
  // NOTE: the legacy "safety" panel was removed — superseded by the dedicated
  // Safety Alerts locked tab (structured output + fixed UI).
  {
    id: "changes",
    title: "What's Changed",
    prompt:
      "Compare the patient's recent clinical data to prior information and list the most important changes in status, therapy, or results. Emphasize deltas that require attention.",
    showInSummary: true,
    autoGenerate: false,
    order: 0,
  },
  {
    id: "snapshot",
    title: "Clinical Snapshot",
    prompt:
      "Create a succinct clinical snapshot covering active problems, current therapies, recent results, and outstanding tasks. Keep it brief and actionable.",
    showInSummary: false,
    autoGenerate: false,
    order: 1,
  },
  {
    id: "standard-medical-summary-free-text",
    title: "Standard Medical Summary (Free Text)",
    prompt: `Write a concise cross-facility medical summary for a physician using the supplied clinical context. Return readable Markdown text only; do not return JSON, code, or a field-by-field object.

Use these headings in order, omitting a section when the record has no relevant data:
## One-line overview
## Cross-facility clinical course
## Active problems
## Key investigations and trends
## Medication review
## Major care timeline

Requirements:
- Stay factual and clinically concise. Use only information in the supplied record; include dates, facilities, values, and units when available. State uncertainty and important record limitations.
- Distinguish confirmed diagnoses in the Problem List or clinical documents from visit/claim ICD codes. Describe a claim-only condition as recorded on a claim, not as confirmed disease.
- For each active problem, briefly state its evidence. Merge duplicates and order by clinical importance.
- Select the 3–6 most relevant laboratory, pathology, or imaging topics. Show actual serial values when present; call something a trend only when there are at least two comparable time points. Do not invent missing tests or values.
- In Medication review, summarize the currently evidenced long-term regimen by treatment area, meaningful date/status-supported changes, and only concrete reconciliation questions tied to this patient's records. NHI prescribing or dispensing history does not prove current use or adherence; merge routine refills and prescribing-clinic/pharmacy duplicates.
- In the timeline, select about 5–8 major turning points rather than every routine visit or refill.
- Do not infer that absent data means absent care, and do not make unsupported diagnoses or treatment recommendations.`,
    showInSummary: false,
    autoGenerate: false,
    order: 2,
  },
]

const DEFAULT_PANELS_EN_PATIENT: BundledInsightPanelConfig[] = [
  {
    id: "health-overview",
    title: "My Health Overview",
    prompt:
      "Using the imported personal health records, write a friendly plain-language overview of my current health: ongoing conditions, current medications, and any recent results that stand out. Define medical terms briefly when needed. End with a reminder that I should discuss specifics with my doctor.",
    showInSummary: true,
    autoGenerate: false,
    order: 0,
  },
  {
    id: "watch-out",
    title: "Things to Watch Out For",
    prompt:
      "Based on my health records, point out items that might deserve attention at my next medical visit — for example, abnormal lab values, medications that interact, vaccinations or screenings that look overdue. Do NOT diagnose; explain why each item matters in plain language and suggest I confirm with my doctor.",
    showInSummary: false,
    autoGenerate: false,
    order: 1,
  },
  {
    id: "questions-doctor",
    title: "Questions for My Doctor",
    prompt:
      "Based on my recent records, draft a concise list of questions I should ask at my next appointment. Cover medications, symptoms, abnormal results, and preventive care. Phrase the questions the way a patient would naturally ask them.",
    showInSummary: false,
    autoGenerate: false,
    order: 2,
  },
  {
    id: "standard-health-summary-free-text",
    title: "My Health Summary (Free Text)",
    prompt: `Using the supplied personal health records, write a calm, easy-to-read health summary for the patient. Return readable Markdown text only; do not return JSON, code, or a field-by-field object.

Use these headings in order, omitting a section when the record has no relevant data:
## My health at a glance
## My recent health journey
## Main health conditions
## Important tests and trends
## My medicines
## Major care timeline
## Questions to discuss with my care team

Requirements:
- Use everyday language at about a junior-high reading level and briefly explain necessary medical terms. Use only facts in the records; include dates and actual values when helpful.
- Distinguish confirmed conditions from diagnoses that appear only as visit/insurance claim codes. Clearly say when something is uncertain.
- For tests, describe the most relevant results and actual serial values. Call something a trend only when there are at least two comparable results; never invent missing tests or values.
- Explain how important recorded medicines may support care and give calm, practical reminders. The record does not prove that a medicine is still being taken. Never tell the patient to start, stop, skip, or change a dose.
- Select only major events for the timeline, not every routine visit or refill.
- Do not assume missing records mean missing care. Avoid alarming language, unsupported diagnoses, prognosis, or treatment advice; suggest discussing uncertainties with the care team.`,
    showInSummary: false,
    autoGenerate: false,
    order: 3,
  },
]

const DEFAULT_PANELS_ZH_MEDICAL: BundledInsightPanelConfig[] = [
  // 註：舊的「安全警示」面板已移除——由獨立的「安全警示」鎖定分頁取代（結構化輸出 + 固定 UI）。
  {
    id: "changes",
    title: "變化摘要",
    prompt:
      "比較病人最近的臨床資料與先前資訊，列出狀態、治療或結果中最重要的變化。強調需要注意的差異。",
    showInSummary: true,
    autoGenerate: false,
    order: 0,
  },
  {
    id: "snapshot",
    title: "臨床快照",
    prompt:
      "建立簡潔的臨床快照，涵蓋活動中的問題、目前治療、近期結果和待辦事項。保持簡短且可執行。",
    showInSummary: false,
    autoGenerate: false,
    order: 1,
  },
  {
    id: "standard-medical-summary-free-text",
    title: "標準醫療摘要（文字版）",
    prompt: `請根據提供的病人臨床資料，產生一份供醫師閱讀的跨院醫療摘要。只輸出清楚可讀的 Markdown 文字；不要輸出 JSON、程式碼或欄位物件。

依序使用以下標題；資料不足的段落可省略：
## 一句話總覽
## 跨院病程摘要
## 主要健康問題
## 重要檢查與趨勢
## 用藥整理
## 重大醫療時間軸

要求：
- 使用簡潔、專業的臨床語氣。只使用資料中的事實；有資料時列出日期、院所、數值與單位，並說明不確定性及重要的資料限制。
- 區分 Problem List 或臨床文件中的確認診斷，與門診／健保申報用的 ICD 碼。若只有申報碼，必須寫成「曾於申報紀錄出現」，不可當成已確認疾病。
- 每個主要健康問題簡述支持證據；合併重複項目，並依臨床重要性排序。
- 選擇 3–6 個最相關的檢驗、病理或影像主題。有序列資料時列出實際數值；至少有兩個可比時間點才稱為趨勢。不可虛構檢查或數值。
- 「用藥整理」要依治療領域整理目前有資料支持的長期用藥、有日期／狀態證據的重要變化，以及只屬於這位病人、有具體紀錄依據的用藥整合待確認項目。健保處方或調劑紀錄不等於目前仍在使用或有遵從性；合併例行續方，也不要把同一處方的醫院與調劑藥局當成重複用藥。
- 時間軸選擇約 5–8 個重要轉折，不要羅列每次例行回診或領藥。
- 不可將「沒有資料」解讀為「沒有就醫或治療」，也不要提出無資料支持的診斷或治療建議。`,
    showInSummary: false,
    autoGenerate: false,
    order: 2,
  },
]

const DEFAULT_PANELS_ZH_PATIENT: BundledInsightPanelConfig[] = [
  {
    id: "health-overview",
    title: "我的健康總覽",
    prompt:
      "請用我匯入的個人健康資料，幫我整理一份白話版的健康總覽：目前的慢性病、正在使用的藥物，以及近期較需要關注的檢驗結果。專有名詞請在括號中簡單說明。最後提醒我若有疑慮應與醫師討論。",
    showInSummary: true,
    autoGenerate: false,
    order: 0,
  },
  {
    id: "watch-out",
    title: "需要留意的事項",
    prompt:
      "根據我的健康資料，列出下次回診時可能值得留意的項目，例如：異常的檢驗值、可能交互作用的藥物、看起來逾期未做的疫苗或健檢。請不要做診斷，僅用白話文說明為什麼這些項目重要，並提醒我向醫師確認。",
    showInSummary: false,
    autoGenerate: false,
    order: 1,
  },
  {
    id: "questions-doctor",
    title: "可以問醫師的問題",
    prompt:
      "根據我的近期健康資料，幫我整理一份下次回診可以詢問醫師的問題清單，涵蓋用藥、症狀、異常檢驗值與預防性檢查。請用病人會自然問出口的口吻。",
    showInSummary: false,
    autoGenerate: false,
    order: 2,
  },
  {
    id: "standard-health-summary-free-text",
    title: "我的健康摘要（文字版）",
    prompt: `請根據提供的個人健康資料，產生一份讓病人容易理解、語氣平穩的健康摘要。只輸出清楚可讀的 Markdown 文字；不要輸出 JSON、程式碼或欄位物件。

依序使用以下標題；資料不足的段落可省略：
## 我的健康總覽
## 近期健康歷程
## 主要健康狀況
## 重要檢查與趨勢
## 我的用藥
## 重大醫療時間軸
## 可以與醫療團隊討論的問題

要求：
- 使用國中程度能理解的白話文，必要的醫學名詞要簡短解釋。只使用資料中的事實；有幫助時列出日期與實際數值。
- 區分已確認的健康問題，與只出現在就醫／健保申報碼的診斷；不確定時要清楚說明。
- 重要檢查要整理最相關的結果與實際序列數值。至少有兩個可比結果才稱為趨勢；不可虛構檢查或數值。
- 對重要的用藥，用白話說明紀錄中它可能支持的照護目標，並提供平穩、實用的提醒。紀錄不能證明目前仍在使用該藥；不可建議病人自行開始、停止、跳過或調整劑量。
- 時間軸只選擇重要事件，不要羅列每次例行回診或領藥。
- 不可將資料缺漏解讀為沒有接受照護。避免令人恐慌的用詞、無支持的診斷、預後或治療建議；不確定處建議與醫療團隊討論。`,
    showInSummary: false,
    autoGenerate: false,
    order: 3,
  },
]

const MAX_PANELS = 999
const ACCOUNT_AUTOSAVE_DELAY_MS = 600

function generatePanelId() {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID()
  }
  return `panel_${Math.random().toString(36).slice(2, 10)}`
}

function getDefaultsFor(language: 'en' | 'zh-TW', audience: Audience): InsightPanelConfig[] {
  let base: BundledInsightPanelConfig[]
  if (language === 'zh-TW') {
    base = audience === 'medical' ? DEFAULT_PANELS_ZH_MEDICAL : DEFAULT_PANELS_ZH_PATIENT
  } else {
    base = audience === 'medical' ? DEFAULT_PANELS_EN_MEDICAL : DEFAULT_PANELS_EN_PATIENT
  }
  return base.map((panel) => ({
    ...panel,
    audience,
    outputFormat: panel.outputFormat ?? "markdown",
    languagePolicy: panel.languagePolicy ?? "interface-language",
    templateLibraryRevision: CLINICAL_INSIGHT_TEMPLATE_LIBRARY_REVISION,
  }))
}

function normalizeInsightPanelConfig(panel: InsightPanelConfig): InsightPanelConfig {
  return {
    ...panel,
    outputFormat: coerceInsightOutputFormat(panel.outputFormat),
    languagePolicy: coerceInsightLanguagePolicy(panel.languagePolicy),
  }
}

function getAllDefaults(language: 'en' | 'zh-TW'): InsightPanelConfig[] {
  return [
    ...getDefaultsFor(language, 'medical'),
    ...getDefaultsFor(language, 'patient'),
  ]
}

function renumberPanelsForAccount(panels: InsightPanelConfig[]): InsightPanelConfig[] {
  return (['medical', 'patient'] as Audience[]).flatMap((panelAudience) => (
    panels
      .filter((panel) => panel.audience === panelAudience)
      .sort((a, b) => a.order - b.order)
      .map((panel, order) => ({ ...panel, order }))
  ))
}

function getPanelFingerprint(panel: InsightPanelConfig): string {
  return JSON.stringify({
    id: panel.id,
    title: panel.title,
    prompt: panel.prompt,
    showInSummary: panel.showInSummary,
    autoGenerate: panel.autoGenerate,
    outputFormat: panel.outputFormat,
    languagePolicy: panel.languagePolicy,
    order: panel.order,
    audience: panel.audience,
    templateLibraryRevision: panel.templateLibraryRevision,
  })
}

const STANDARD_SUMMARY_TEMPLATE_ID: Record<Audience, string> = {
  medical: "standard-medical-summary-free-text",
  patient: "standard-health-summary-free-text",
}

/**
 * Add newly bundled library templates once per audience without resurrecting a
 * template the user later deletes. The revision is copied to every panel so it
 * survives account sync even after the bundled template itself is removed.
 */
export function migrateClinicalInsightTemplateLibrary(
  panels: InsightPanelConfig[],
  language: 'en' | 'zh-TW',
): { panels: InsightPanelConfig[]; changed: boolean } {
  let next = [...panels]
  let changed = false

  ;(['medical', 'patient'] as Audience[]).forEach((audience) => {
    const audiencePanels = next.filter((panel) => panel.audience === audience)
    if (audiencePanels.length === 0) return
    const isCurrent = audiencePanels.some(
      (panel) => (panel.templateLibraryRevision ?? 0) >= CLINICAL_INSIGHT_TEMPLATE_LIBRARY_REVISION,
    )
    if (isCurrent) return

    const bundledTemplate = getDefaultsFor(language, audience).find(
      (panel) => panel.id === STANDARD_SUMMARY_TEMPLATE_ID[audience],
    )
    if (bundledTemplate && !audiencePanels.some((panel) => panel.id === bundledTemplate.id)) {
      const nextOrder = Math.max(-1, ...audiencePanels.map((panel) => panel.order)) + 1
      next.push({ ...bundledTemplate, order: nextOrder })
    }
    next = next.map((panel) => panel.audience === audience
      ? { ...panel, templateLibraryRevision: CLINICAL_INSIGHT_TEMPLATE_LIBRARY_REVISION }
      : panel)
    changed = true
  })

  return { panels: next, changed }
}

function panelsEqualDefaults(panels: InsightPanelConfig[], language: 'en' | 'zh-TW', audience: Audience): boolean {
  const defaults = getDefaultsFor(language, audience)
  const current = panels.filter((p) => p.audience === audience).sort((a, b) => a.order - b.order)
  if (current.length !== defaults.length) return false
  return current.every((p, i) => {
    const d = defaults[i]
    return d && p.id === d.id && p.title === d.title && p.prompt === d.prompt &&
      p.showInSummary === d.showInSummary && p.autoGenerate === d.autoGenerate
      && p.outputFormat === d.outputFormat && p.languagePolicy === d.languagePolicy
  })
}

export function getDefaultClinicalInsightPanels(language: 'en' | 'zh-TW' = 'en', audience: Audience = 'medical'): InsightPanelConfig[] {
  return getDefaultsFor(language, audience)
}

type ClinicalInsightsConfigContextValue = {
  panels: InsightPanelConfig[]
  guestEditingApproved: boolean
  approveGuestEditing: () => void
  addPanel: (initial?: Partial<Pick<InsightPanelConfig, "title" | "prompt" | "showInSummary" | "autoGenerate" | "outputFormat" | "languagePolicy">>) => string | null
  updatePanel: (id: string, patch: Partial<Omit<InsightPanelConfig, "audience">>) => void
  updatePanelAndSave: (id: string, patch: Partial<Omit<InsightPanelConfig, "audience">>) => Promise<void>
  removePanel: (id: string) => void
  restorePanel: (panel: InsightPanelConfig) => void
  resetPanels: () => Promise<void>
  savePanels: () => Promise<boolean>
  maxPanels: number
  reorderPanels: (orderedIds: string[]) => void
  isSaving: boolean
  isLoading: boolean
  syncStatus: ClinicalInsightTemplateSyncStatus
  lastSavedAt: Date | null
}

export type ClinicalInsightTemplateSyncStatus = "idle" | "dirty" | "saving" | "saved" | "error"

type PendingPanelMutation = {
  panel: InsightPanelConfig | null
  revision: number
}

function getPanelLibraryDiff(
  before: InsightPanelConfig[],
  after: InsightPanelConfig[],
): Array<{ id: string; panel: InsightPanelConfig | null }> {
  const beforeById = new Map(before.map((panel) => [panel.id, panel]))
  const afterById = new Map(after.map((panel) => [panel.id, panel]))
  const mutations: Array<{ id: string; panel: InsightPanelConfig | null }> = []

  beforeById.forEach((_panel, id) => {
    if (!afterById.has(id)) mutations.push({ id, panel: null })
  })
  afterById.forEach((panel, id) => {
    const previous = beforeById.get(id)
    if (!previous || getPanelFingerprint(previous) !== getPanelFingerprint(panel)) {
      mutations.push({ id, panel })
    }
  })
  return mutations
}

function overlayPendingPanelMutations(
  panels: InsightPanelConfig[],
  pending: Map<string, PendingPanelMutation>,
): InsightPanelConfig[] {
  const byId = new Map(panels.map((panel) => [panel.id, panel]))
  pending.forEach(({ panel }, id) => {
    if (panel) byId.set(id, panel)
    else byId.delete(id)
  })
  return [...byId.values()]
}

const ClinicalInsightsConfigContext = createContext<ClinicalInsightsConfigContextValue | null>(null)

export function ClinicalInsightsConfigProvider({ children }: { children: ReactNode }) {
  const { locale } = useLanguage()
  const { audience } = useAudience()
  const { user, loading: authLoading } = useAuth()
  const currentLang: 'en' | 'zh-TW' = locale === "zh-TW" ? "zh-TW" : "en"

  const [allPanels, setAllPanels] = useState<InsightPanelConfig[]>(() => getAllDefaults('en'))
  const allPanelsRef = useRef<InsightPanelConfig[]>(allPanels)
  const [hasLoadedFromStorage, setHasLoadedFromStorage] = useState(false)
  const [customByAudience, setCustomByAudience] = useState<Record<Audience, boolean>>({ medical: false, patient: false })
  const [hasReceivedAccountSnapshot, setHasReceivedAccountSnapshot] = useState(false)
  const [guestEditingApproved, setGuestEditingApproved] = useState(false)
  const [syncStatus, setSyncStatus] = useState<ClinicalInsightTemplateSyncStatus>("idle")
  const syncStatusRef = useRef<ClinicalInsightTemplateSyncStatus>("idle")
  const [lastSavedAt, setLastSavedAt] = useState<Date | null>(null)
  const [pendingMutationVersion, setPendingMutationVersion] = useState(0)
  const pendingMutationsRef = useRef<Map<string, PendingPanelMutation>>(new Map())
  const mutationRevisionRef = useRef(0)
  const savePromiseRef = useRef<Promise<boolean> | null>(null)
  const [loadedOwner, setLoadedOwner] = useState<string | null | undefined>(undefined)
  const loadedOwnerRef = useRef<string | null | undefined>(undefined)

  const updateSyncStatus = useCallback((next: ClinicalInsightTemplateSyncStatus) => {
    syncStatusRef.current = next
    setSyncStatus(next)
  }, [])

  const queuePanelMutations = useCallback((
    before: InsightPanelConfig[],
    after: InsightPanelConfig[],
  ) => {
    if (!user?.uid) return
    const mutations = getPanelLibraryDiff(before, after)
    if (mutations.length === 0) return

    let changed = false
    mutations.forEach(({ id, panel }) => {
      const existing = pendingMutationsRef.current.get(id)
      const existingFingerprint = existing?.panel ? getPanelFingerprint(existing.panel) : null
      const nextFingerprint = panel ? getPanelFingerprint(panel) : null
      if (existing && existingFingerprint === nextFingerprint) return
      mutationRevisionRef.current += 1
      pendingMutationsRef.current.set(id, {
        panel,
        revision: mutationRevisionRef.current,
      })
      changed = true
    })

    if (!changed) return
    setPendingMutationVersion((version) => version + 1)
    if (syncStatusRef.current !== "saving") updateSyncStatus("dirty")
  }, [updateSyncStatus, user?.uid])

  const commitLocalPanels = useCallback((
    update: (current: InsightPanelConfig[]) => InsightPanelConfig[],
  ): InsightPanelConfig[] => {
    const before = allPanelsRef.current
    const after = renumberPanelsForAccount(update(before))
    const changed = getPanelLibraryDiff(before, after).length > 0
    if (!changed) return before
    allPanelsRef.current = after
    setAllPanels(after)
    queuePanelMutations(before, after)
    return after
  }, [queuePanelMutations])

  // Treat every account and the signed-out state as separate storage owners.
  // The rendered panel list is hidden as soon as the auth owner changes, so a
  // shared workstation never paints the previous account's templates while
  // the next account snapshot is loading.
  useEffect(() => {
    if (authLoading) return
    const nextOwner = user?.uid ?? null
    if (loadedOwnerRef.current === undefined) {
      loadedOwnerRef.current = nextOwner
      setLoadedOwner(nextOwner)
      return
    }
    if (loadedOwnerRef.current === nextOwner) return

    loadedOwnerRef.current = nextOwner
    setLoadedOwner(nextOwner)
    setHasReceivedAccountSnapshot(false)
    setHasLoadedFromStorage(false)
    pendingMutationsRef.current.clear()
    mutationRevisionRef.current = 0
    savePromiseRef.current = null
    setPendingMutationVersion((version) => version + 1)
    updateSyncStatus("idle")
    setLastSavedAt(null)
    const defaults = getAllDefaults(currentLang)
    allPanelsRef.current = defaults
    setAllPanels(defaults)
    setCustomByAudience({ medical: false, patient: false })
    setGuestEditingApproved(false)
  }, [authLoading, currentLang, updateSyncStatus, user?.uid])

  // Guests deliberately start from in-memory defaults. Their edits last only
  // for the current page lifetime and are never promoted into whichever
  // account signs in next on this shared workstation.
  useEffect(() => {
    if (authLoading) return
    if (hasLoadedFromStorage) return
    const defaults = getAllDefaults(currentLang)
    allPanelsRef.current = defaults
    // Initializing an auth-scoped library is intentionally effect-driven.
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setAllPanels(defaults)
    setCustomByAudience({ medical: false, patient: false })
    setHasLoadedFromStorage(true)
  }, [authLoading, hasLoadedFromStorage, user?.uid, currentLang])

  // Firestore subscription
  useEffect(() => {
    if (!user?.uid || !hasLoadedFromStorage) return

    const unsubscribe = subscribeToClinicalInsightPanels(user.uid, (incoming: InsightPanelConfig[]) => {
      // Keep one-time cleanup and bundled-template migrations idempotent. The
      // revision marker also means deleting a bundled template is respected.
      const stripped = stripLegacySafetyPanels(incoming)
      const updated = stripped.map(normalizeInsightPanelConfig)
      let accountLibrary: InsightPanelConfig[]
      let needsAccountMaintenance = updated.length < incoming.length
        || updated.some((panel, index) => getPanelFingerprint(panel) !== getPanelFingerprint(stripped[index]))
        || incoming.length > MAX_PANELS
        || incoming.length === 0

      if (updated.length === 0) {
        accountLibrary = getAllDefaults(currentLang)
      } else {
        const seen = new Set(updated.map((p) => p.audience))
        const merged: InsightPanelConfig[] = [...updated.slice(0, MAX_PANELS)]
        ;(['medical', 'patient'] as Audience[]).forEach((aud) => {
          if (!seen.has(aud)) {
            merged.push(...getDefaultsFor(currentLang, aud))
            needsAccountMaintenance = true
          }
        })
        const migration = migrateClinicalInsightTemplateLibrary(merged, currentLang)
        accountLibrary = migration.panels
        needsAccountMaintenance ||= migration.changed
      }

      const nextPanels = overlayPendingPanelMutations(
        renumberPanelsForAccount(accountLibrary),
        pendingMutationsRef.current,
      )
      allPanelsRef.current = nextPanels
      setAllPanels(nextPanels)
      setCustomByAudience({
        medical: !panelsEqualDefaults(nextPanels, currentLang, 'medical'),
        patient: !panelsEqualDefaults(nextPanels, currentLang, 'patient'),
      })

      setHasReceivedAccountSnapshot(true)

      if (needsAccountMaintenance) {
        queuePanelMutations(incoming, accountLibrary)
      } else if (pendingMutationsRef.current.size === 0) {
        updateSyncStatus("saved")
      }
    })

    return () => unsubscribe()
  }, [currentLang, hasLoadedFromStorage, queuePanelMutations, updateSyncStatus, user?.uid])

  // On language change: swap defaults for any audience that isn't customized
  useEffect(() => {
    if (!hasLoadedFromStorage) return
    if (user?.uid && !hasReceivedAccountSnapshot) return
    // Language is external preference state; replace only bundled defaults
    // while preserving each audience's customized panels.
    commitLocalPanels((current) => {
      const next = current.filter((panel) => customByAudience[panel.audience])
      ;(['medical', 'patient'] as Audience[]).forEach((panelAudience) => {
        if (!customByAudience[panelAudience]) {
          next.push(...getDefaultsFor(currentLang, panelAudience))
        }
      })
      return next
    })
  }, [
    commitLocalPanels,
    currentLang,
    customByAudience,
    hasLoadedFromStorage,
    hasReceivedAccountSnapshot,
    user?.uid,
  ])

  const activeOwner = user?.uid ?? null
  const ownerMatches = loadedOwner === activeOwner
  const isLoading = authLoading
    || !ownerMatches
    || !hasLoadedFromStorage
    || Boolean(user?.uid && !hasReceivedAccountSnapshot)
  const panels = useMemo(
    () => isLoading
      ? []
      : allPanels.filter((p) => p.audience === audience).sort((a, b) => a.order - b.order),
    [allPanels, audience, isLoading],
  )

  const savePanels = useCallback(async (): Promise<boolean> => {
    if (!user?.uid || isLoading) return false
    if (savePromiseRef.current) return savePromiseRef.current

    const mutationEntries = [...pendingMutationsRef.current.entries()]
    if (mutationEntries.length === 0) {
      updateSyncStatus("saved")
      return true
    }

    const ownerId = user.uid
    const upserts = mutationEntries
      .map(([, mutation]) => mutation.panel)
      .filter((panel): panel is InsightPanelConfig => panel !== null)
    const deleteIds = mutationEntries
      .filter(([, mutation]) => mutation.panel === null)
      .map(([id]) => id)

    updateSyncStatus("saving")
    const savePromise = applyClinicalInsightPanelChanges(ownerId, upserts, deleteIds)
    savePromiseRef.current = savePromise

    try {
      const saved = await savePromise
      if (loadedOwnerRef.current !== ownerId) return false
      if (!saved) {
        updateSyncStatus("error")
        return false
      }

      mutationEntries.forEach(([id, savedMutation]) => {
        if (pendingMutationsRef.current.get(id)?.revision === savedMutation.revision) {
          pendingMutationsRef.current.delete(id)
        }
      })
      setPendingMutationVersion((version) => version + 1)
      setLastSavedAt(new Date())
      updateSyncStatus(pendingMutationsRef.current.size > 0 ? "dirty" : "saved")
      return true
    } catch (error) {
      if (loadedOwnerRef.current === ownerId) {
        console.error('[Clinical Insights] Account save failed:', error)
        updateSyncStatus("error")
      }
      return false
    } finally {
      if (savePromiseRef.current === savePromise) savePromiseRef.current = null
    }
  }, [isLoading, updateSyncStatus, user])

  // Quiet-period autosave. Closing the manager does not interrupt this because
  // the provider lives at the workspace level, outside the drawer.
  useEffect(() => {
    if (!user?.uid || isLoading || syncStatus !== "dirty") return
    if (pendingMutationsRef.current.size === 0) return
    const timer = window.setTimeout(() => {
      void savePanels()
    }, ACCOUNT_AUTOSAVE_DELAY_MS)
    return () => window.clearTimeout(timer)
  }, [isLoading, pendingMutationVersion, savePanels, syncStatus, user?.uid])

  // Warn only when the entire page is being discarded. Closing the template
  // drawer is safe: pending writes continue in this provider.
  useEffect(() => {
    if (!user?.uid || pendingMutationsRef.current.size === 0) return
    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      event.preventDefault()
    }
    window.addEventListener("beforeunload", handleBeforeUnload)
    return () => window.removeEventListener("beforeunload", handleBeforeUnload)
  }, [pendingMutationVersion, user?.uid])

  const addPanel = (initial?: Partial<Pick<InsightPanelConfig, "title" | "prompt" | "showInSummary" | "autoGenerate" | "outputFormat" | "languagePolicy">>) => {
    if (isLoading) return null
    const audienceCount = allPanelsRef.current.filter((p) => p.audience === audience).length
    if (audienceCount >= MAX_PANELS) return null
    const suffix = audienceCount + 1
    const newPanel: InsightPanelConfig = {
      id: generatePanelId(),
      title: initial?.title ?? `Custom Panel ${suffix}`,
      prompt: initial?.prompt ?? "Describe the key clinical insights for this focus area using the provided context.",
      showInSummary: initial?.showInSummary ?? false,
      autoGenerate: initial?.autoGenerate ?? false,
      outputFormat: initial?.outputFormat ?? "plain-text",
      languagePolicy: initial?.languagePolicy ?? "follow-template",
      order: audienceCount,
      audience,
      templateLibraryRevision: CLINICAL_INSIGHT_TEMPLATE_LIBRARY_REVISION,
    }
    commitLocalPanels((current) => [...current, newPanel])
    setCustomByAudience((prev) => ({ ...prev, [audience]: true }))
    return newPanel.id
  }

  const normalizePatch = (patch: Partial<Omit<InsightPanelConfig, "audience">>) => {
    if (patch.showInSummary === false) return { ...patch, autoGenerate: false }
    if (patch.autoGenerate === true) return { ...patch, showInSummary: true }
    return patch
  }

  const applyConstrainedPatch = (
    source: InsightPanelConfig[],
    id: string,
    patch: Partial<Omit<InsightPanelConfig, "audience">>,
  ) => {
    const target = source.find((panel) => panel.id === id)
    if (!target) return source
    const normalized = normalizePatch(patch)
    const audiencePanels = source.filter((panel) => panel.audience === target.audience && panel.id !== id)
    if (
      normalized.showInSummary === true &&
      !target.showInSummary &&
      audiencePanels.filter((panel) => panel.showInSummary).length >= MAX_SUMMARY_INSIGHT_MODULES
    ) return source
    if (
      normalized.autoGenerate === true &&
      !target.autoGenerate &&
      audiencePanels.filter((panel) => panel.showInSummary && panel.autoGenerate).length >= MAX_AUTO_INSIGHT_MODULES
    ) return source
    return source.map((panel) => (
      panel.id === id
        ? { ...panel, ...normalized, id: panel.id, audience: panel.audience }
        : panel
    ))
  }

  const updatePanel = (id: string, patch: Partial<Omit<InsightPanelConfig, "audience">>) => {
    if (isLoading) return
    commitLocalPanels((current) => applyConstrainedPatch(current, id, patch))
    setCustomByAudience((prev) => ({ ...prev, [audience]: true }))
  }

  const updatePanelAndSave = async (id: string, patch: Partial<Omit<InsightPanelConfig, "audience">>) => {
    updatePanel(id, patch)
    await savePanels()
  }

  const removePanel = (id: string) => {
    if (isLoading) return
    commitLocalPanels((current) => {
      const target = current.find((panel) => panel.id === id)
      if (!target) return current
      const audienceCount = current.filter((panel) => panel.audience === target.audience).length
      if (audienceCount <= 1) return current // keep at least one per audience
      return current.filter((panel) => panel.id !== id)
    })
    setCustomByAudience((prev) => ({ ...prev, [audience]: true }))
  }

  const restorePanel = (panel: InsightPanelConfig) => {
    if (isLoading || allPanelsRef.current.some((current) => current.id === panel.id)) return
    commitLocalPanels((current) => [...current, panel])
    setCustomByAudience((prev) => ({ ...prev, [panel.audience]: true }))
  }

  const resetPanels = async () => {
    if (isLoading) return
    const defaults = getDefaultsFor(currentLang, audience)
    commitLocalPanels((current) => [
      ...current.filter((panel) => panel.audience !== audience),
      ...defaults,
    ])
    setCustomByAudience((prev) => ({ ...prev, [audience]: false }))
    if (user?.uid) await savePanels()
  }

  const reorderPanels = (orderedIds: string[]) => {
    if (isLoading) return
    commitLocalPanels((current) => {
      if (!Array.isArray(orderedIds) || orderedIds.length === 0) return current
      const idSet = new Set(orderedIds)
      const filtered = current.filter((panel) => panel.audience === audience)
      const ordered = orderedIds
        .map((id) => filtered.find((panel) => panel.id === id))
        .filter((panel): panel is InsightPanelConfig => Boolean(panel))
      const orderById = new Map(ordered.map((panel, index) => [panel.id, index]))
      // Reassign order within current audience; preserve other audience untouched.
      return current.map((panel) => {
        if (panel.audience !== audience) return panel
        if (!idSet.has(panel.id)) return panel
        return { ...panel, order: orderById.get(panel.id) ?? panel.order }
      })
    })
    setCustomByAudience((prev) => ({ ...prev, [audience]: true }))
  }

  const approveGuestEditing = useCallback(() => {
    if (!user?.uid) setGuestEditingApproved(true)
  }, [user?.uid])

  const value = {
    panels,
    guestEditingApproved,
    approveGuestEditing,
    addPanel,
    updatePanel,
    updatePanelAndSave,
    removePanel,
    restorePanel,
    resetPanels,
    savePanels,
    reorderPanels,
    maxPanels: MAX_PANELS,
    isSaving: syncStatus === "saving",
    isLoading,
    syncStatus,
    lastSavedAt,
  }

  return <ClinicalInsightsConfigContext.Provider value={value}>{children}</ClinicalInsightsConfigContext.Provider>
}

export function useClinicalInsightsConfig() {
  const context = useContext(ClinicalInsightsConfigContext)
  if (!context) {
    throw new Error("useClinicalInsightsConfig must be used within ClinicalInsightsConfigProvider")
  }
  return context
}
