// Pre-generated AI snapshots for the DEMO bundle (示範資料, demo-patient-1).
//
// Why: the demo bundle is frozen, so its AI output is effectively a constant —
// re-generating it for every first-time visitor burns two AI calls per visit
// (and the visitor's free-tier quota) to recompute a known answer, and exposes
// the first impression to transient model failures. These snapshots are REAL
// AI-authored raw outputs (same schema the live models produce), written
// against the catalog keys that buildSourceCatalog() derives from
// public/demo/demo-bundle.json.
//
// Provenance (2026-08-13): generated by gemini-3.1-flash-lite via the
// production proxy, using the app's real prompt builders and the default
// (newPatient) data selection. Each candidate run was audited (scripts + human)
// for citation relevance, evidence existence, trend faithfulness and medication
// pharmacology before being frozen here. Editorial corrections only clarify
// claim-vs-confirmed diagnoses, lab direction and medication class; they do not
// add uncited patient facts. Live patients still use the model-generated path.
// Only the safety results are post-processed by the same
// filterDuplicateFalsePositives guard the live path applies.
//
// They deliberately store the RAW pre-parse shape, NOT the finalized result:
// the hooks feed them through the exact same parse → finalize/verify pipeline
// as a live reply, so citation resolution, verification marking and navigation
// stay honest. If the demo bundle ever changes, stale citations surface as
// amber "unverified" pills — the visible signal to regenerate this file (run
// scripts/validate-demo-snapshots.ts, or just re-author).
//
// Scope guards (enforced by the hooks): demo patient + supported locale + no
// cached result. A retained model preference never causes an automatic live call;
// pressing 重新產生 explicitly still runs the selected model.
import type {
  MedicalSummaryAiResult,
  MedicalSummaryGeneration,
  SummarySourceCatalogEntry,
} from '@/src/core/entities/medical-summary.entity'
import type {
  SafetyScanGeneration,
  SafetyScanResultInput,
} from '@/src/core/entities/safety-alert.entity'

export const DEMO_PATIENT_ID = 'demo-patient-1'

export const DEMO_MEDICAL_SUMMARY_GENERATION = {
  source: 'pre-generated',
  modelId: 'gemini-3.1-flash-lite',
  modelName: 'Gemini 3.1 Flash-Lite',
} as const satisfies MedicalSummaryGeneration

export const DEMO_SAFETY_SCAN_GENERATION = {
  source: 'pre-generated',
  modelId: 'gemini-3.1-flash-lite',
  modelName: 'Gemini 3.1 Flash-Lite',
} as const satisfies SafetyScanGeneration

export const DEMO_CLINICAL_INSIGHT_GENERATION = {
  source: 'pre-generated',
  modelId: 'gemini-3.1-flash-lite',
  modelName: 'Gemini 3.1 Flash-Lite',
  provider: 'gemini',
} as const

type Audience = 'medical' | 'patient'
type SnapshotLocale = 'en' | 'zh-TW'

// Snapshot citations are authored against the default demo catalog, whose
// short keys are deterministic only while the selected AI scope is unchanged.
// A retained small-context model may legitimately prioritize the same FHIR
// resources and renumber those keys. Resource ids are the stable bridge that
// lets the bundled snapshot keep pointing at the same evidence in either view.
const DEMO_SNAPSHOT_RESOURCE_ID_BY_KEY: Readonly<Record<string, string>> = {
  D1: 'demo-documentreference-1',
  E1: 'demo-encounter-30',
  E2: 'demo-encounter-31',
  E3: 'demo-encounter-32',
  E4: 'demo-encounter-33',
  E5: 'demo-encounter-34',
  E6: 'demo-encounter-35',
  E9: 'demo-encounter-38',
  E10: 'demo-encounter-39',
  E12: 'demo-encounter-27',
  E13: 'demo-encounter-28',
  E16: 'demo-encounter-24',
  E17: 'demo-encounter-9',
  E19: 'demo-encounter-11',
  E22: 'demo-encounter-12',
  E23: 'demo-encounter-13',
  K1: 'demo-careplan-1',
  K2: 'demo-careplan-2',
  L15: 'demo-diagnosticreport-1',
  L26: 'demo-diagnosticreport-3',
  L27: 'demo-diagnosticreport-2',
  L28: 'demo-diagnosticreport-7',
  M1: 'demo-medicationrequest-106',
  M2: 'demo-medicationrequest-107',
  M3: 'demo-medicationrequest-108',
  M4: 'demo-medicationrequest-109',
  M5: 'demo-medicationrequest-110',
  M6: 'demo-medicationrequest-111',
  M7: 'demo-medicationrequest-112',
  M8: 'demo-medicationrequest-113',
  M9: 'demo-medicationrequest-114',
  M10: 'demo-medicationrequest-115',
  M11: 'demo-medicationrequest-117',
  M12: 'demo-medicationrequest-118',
  M13: 'demo-medicationrequest-119',
  M14: 'demo-medicationrequest-120',
  M15: 'demo-medicationrequest-121',
  M16: 'demo-medicationrequest-122',
  M17: 'demo-medicationrequest-123',
  M18: 'demo-medicationrequest-124',
  M19: 'demo-medicationrequest-125',
  M20: 'demo-medicationrequest-126',
  M21: 'demo-medicationrequest-127',
  O6: 'demo-observation-6',
  O7: 'demo-observation-7',
  O8: 'demo-observation-8',
  O9: 'demo-observation-9',
  O10: 'demo-observation-10',
  O14: 'demo-observation-14',
  O17: 'demo-observation-25',
  O18: 'demo-observation-26',
  O19: 'demo-observation-27',
  O20: 'demo-observation-28',
  O23: 'demo-observation-37',
}

/** Re-key only citation fields; narrative/evidence text remains untouched. */
export function remapDemoSnapshotSourceKeys<T>(
  snapshot: T,
  catalog: SummarySourceCatalogEntry[],
): T {
  const currentKeyByResourceId = new Map(
    catalog.map((source) => [source.resourceId, source.key]),
  )
  const remapKey = (key: string) => {
    const resourceId = DEMO_SNAPSHOT_RESOURCE_ID_BY_KEY[key]
    return resourceId ? currentKeyByResourceId.get(resourceId) ?? key : key
  }
  const visit = (value: unknown, field?: string): unknown => {
    if (Array.isArray(value)) {
      return field === 'sources'
        ? value.map((item) => typeof item === 'string' ? remapKey(item) : item)
        : value.map((item) => visit(item))
    }
    if (!value || typeof value !== 'object') {
      return (field === 'ref' || field === 'source') && typeof value === 'string'
        ? remapKey(value)
        : value
    }
    return Object.fromEntries(
      Object.entries(value).map(([key, item]) => [key, visit(item, key)]),
    )
  }
  return visit(snapshot) as T
}

// Free-form custom-module snapshots are intentionally separate from the
// structured medical-summary snapshots. They preload only while the matching
// default prompt and default Insights model are still selected.
const demoClinicalInsightSnapshotsZhTw: Record<Audience, Record<string, { prompt: string; text: string }>> = {
  medical: {
    changes: {
      prompt: '比較病人最近的臨床資料與先前資訊，列出狀態、治療或結果中最重要的變化。強調需要注意的差異。',
      text: [
        '### 近期重要變化',
        '- **最新就醫與用藥已更新至 2026-08-12**：最新門診申報含肺炎、血液疾病與貧血代碼，並有 ACTEIN 21 天處方；申報診斷仍需回原病歷確認。',
        '- **7–8 月有多項近期調劑**：包含認知／情緒、攝護腺／膀胱、青光眼、腎臟／代謝與腸胃用藥，藥物整合時應以實際藥袋核對。',
        '- **腎功能小幅惡化**：2026-05-25 至 06-02 的 Creatinine 1.88→1.93 mg/dL、eGFR 33→32 mL/min/1.73m²。',
        '- **貧血有改善但尚未正常化**：Hb 11.2→12.1 g/dL，仍低於檢驗單參考區間。',
        '- **胸部影像仍需結合臨床判讀**：06-02 X 光記錄支氣管周圍浸潤、雙下肺斑片狀病灶、雙側肋膜積液及邊緣性心臟擴大。',
      ].join('\n'),
    },
  },
  patient: {
    'health-overview': {
      prompt: '請用我匯入的個人健康資料，幫我整理一份白話版的健康總覽：目前的慢性病、正在使用的藥物，以及近期較需要關注的檢驗結果。專有名詞請在括號中簡單說明。最後提醒我若有疑慮應與醫師討論。',
      text: [
        '### 最近值得注意的健康變化',
        '- 您的就醫與用藥紀錄已更新到 2026-08-12，7–8 月有攝護腺／膀胱、眼科、腎臟／血糖、甲狀腺、尿酸、腸胃及其他近期用藥。',
        '- 腎功能在 5 月 25 日到 6 月 2 日之間有小幅變化（eGFR 33→32），請按照原醫療團隊安排繼續追蹤。',
        '- 血色素由 11.2 升至 12.1 g/dL，但仍低於檢驗單參考值，可在回診時請醫師說明後續計畫。',
        '- 6–8 月的門診申報多次出現肺炎、多發性骨髓瘤與貧血代碼；申報碼不是完整診斷報告，請向原看診醫師確認哪些診斷已正式確立。',
        '- 6 月 2 日胸部 X 光曾記錄肺部病灶與雙側肋膜積液；若有發燒、喘或其他急性不適，請及時就醫。',
        '',
        '這是依健康存摺試用資料整理的提醒；實際病情與任何用藥調整，請和您的醫療團隊確認，不要自行停藥。',
      ].join('\n'),
    },
  },
}

const demoClinicalInsightSnapshotsEn: Record<Audience, Record<string, { prompt: string; text: string }>> = {
  medical: {
    changes: {
      prompt: "Compare the patient's recent clinical data to prior information and list the most important changes in status, therapy, or results. Emphasize deltas that require attention.",
      text: [
        '### Recent important changes',
        '- **Encounter and medication records now extend through 2026-08-12**: the latest outpatient claim includes pneumonia, blood-disorder, and anemia codes, plus a 21-day ACTEIN prescription. Claims diagnoses still require confirmation in the source medical record.',
        '- **Several medications were dispensed in July and August**: recent records span cognition/mood, prostate/bladder, glaucoma, renal/metabolic, and gastrointestinal treatment areas. Reconcile the current regimen against the patient’s actual medication packages.',
        '- **Renal indices declined slightly**: from 2026-05-25 to 06-02, creatinine changed from 1.88 to 1.93 mg/dL and eGFR from 33 to 32 mL/min/1.73m².',
        '- **Anemia indices improved but did not normalize**: hemoglobin increased from 11.2 to 12.1 g/dL and remained below the reported reference interval.',
        '- **Chest imaging still requires clinical correlation**: the 06-02 radiograph described peribronchial infiltration, patchy bilateral lower-lung opacities, bilateral pleural effusions, and borderline cardiomegaly.',
      ].join('\n'),
    },
  },
  patient: {
    'health-overview': {
      prompt: 'Using the imported personal health records, write a friendly plain-language overview of my current health: ongoing conditions, current medications, and any recent results that stand out. Define medical terms briefly when needed. End with a reminder that I should discuss specifics with my doctor.',
      text: [
        '### Recent health changes worth noting',
        '- Your encounter and medication records now extend through 2026-08-12. Recent prescriptions include medicines related to the prostate/bladder, eyes, kidneys/blood glucose, thyroid, uric acid, and digestive system.',
        '- Kidney-function values changed slightly between May 25 and June 2 (eGFR 33→32). Continue follow-up as arranged by your care team.',
        '- Hemoglobin increased from 11.2 to 12.1 g/dL but remained below the laboratory report’s reference value. Ask your clinician about the follow-up plan.',
        '- Claims from June through August repeatedly include codes for pneumonia, multiple myeloma, and anemia. Claims codes are not complete diagnostic reports, so ask the treating clinician which diagnoses are confirmed.',
        '- A June 2 chest radiograph described lung findings and fluid around both lungs. Seek timely care for fever, shortness of breath, or other acute symptoms.',
        '',
        'This overview is based on the demo personal health records. Discuss your actual condition and any medication changes with your care team, and do not stop medication on your own.',
      ].join('\n'),
    },
  },
}

export const demoClinicalInsightSnapshots: Record<SnapshotLocale, Record<Audience, Record<string, { prompt: string; text: string }>>> = {
  'zh-TW': demoClinicalInsightSnapshotsZhTw,
  en: demoClinicalInsightSnapshotsEn,
}

/**
 * Return a bundled custom-insight snapshot solely from demo identity and panel
 * identity. Model preference is intentionally absent: retaining a model from a
 * real patient must never turn loading the frozen demo into an automatic cloud
 * request. Manual regeneration remains model-aware in the caller.
 */
export function getDemoClinicalInsightSnapshot(
  patientId: string,
  audience: Audience,
  locale: SnapshotLocale,
  panelId: string,
) {
  return patientId === DEMO_PATIENT_ID
    ? demoClinicalInsightSnapshots[locale][audience][panelId]
    : undefined
}

const demoMedicalSummarySnapshotsZhTw: Record<Audience, MedicalSummaryAiResult> = {
  medical: {
    headline: '94歲男性，慢性腎臟病第3b期合併貧血；近期申報紀錄反覆出現肺炎與血液疾病診斷碼。',
    summary: [
      { text: '患者為94歲男性，已納入', emphasis: false, sources: [] },
      { text: '慢性腎臟病照護計畫', emphasis: true, sources: ['K1', 'K2'] },
      { text: '；2026-05-25至06-02腎功能呈', emphasis: false, sources: [] },
      { text: 'Creatinine 1.88→1.93 mg/dL、eGFR 33→32 mL/min/1.73m²', emphasis: true, sources: ['O6', 'O7', 'O17', 'O18'] },
      { text: '。2026-06至08月多次門診申報同時列有', emphasis: false, sources: [] },
      { text: '肺炎、多發性骨髓瘤與貧血', emphasis: true, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: '；這些屬申報診斷，仍需回原病歷確認實際診斷、分期與治療狀態。', emphasis: false, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: '2026-06-02胸部X光另見支氣管周圍浸潤、雙下肺斑片狀病灶、雙側肋膜變化合併積液及邊緣性心臟擴大。', emphasis: false, sources: ['L15'] },
    ],
    investigations: [
      {
        label: '腎功能（Creatinine／eGFR）',
        kind: 'lab',
        direction: 'worsening',
        trend: 'Creatinine 1.88→1.93 mg/dL；eGFR 33→32 mL/min/1.73m²',
        interpretation: '8天內腎功能指標小幅惡化；既有第3b期慢性腎臟病需持續依趨勢追蹤。',
        sources: ['O6', 'O7', 'O17', 'O18'],
      },
      {
        label: '貧血指標（Hb／HCT）',
        kind: 'lab',
        direction: 'improving',
        trend: 'Hb 11.2→12.1 g/dL；HCT 35.8→37.2%',
        interpretation: '數值較前回升，但Hb仍低於13.5–17.5 g/dL參考區間，貧血尚未正常化。',
        sources: ['O8', 'O9', 'O19', 'O20'],
      },
      {
        label: '血糖（HbA1c／餐後血糖）',
        kind: 'lab',
        direction: 'stable',
        trend: 'HbA1c 6.6%；餐後血糖126→124 mg/dL',
        interpretation: '兩次餐後血糖接近，暫無明顯方向；HbA1c僅一筆，應依個別目標判讀。',
        sources: ['O10', 'O14', 'O23'],
      },
      {
        label: '胸部影像',
        kind: 'imaging',
        direction: 'single',
        trend: '支氣管周圍浸潤、雙下肺斑片狀病灶、雙側肋膜變化合併積液',
        interpretation: '此列僅呈現最新影像所述結果，未據此推定病因或長期變化。',
        sources: ['L15'],
      },
    ],
    medicationEducation: [],
    medicationReview: {
      overview:
        '2026年7至8月紀錄涵蓋呼吸道、認知／情緒、排尿、眼科、腎臟／代謝、甲狀腺／尿酸及腸胃用藥；跨院所管理時應以實際藥袋核對目前服用清單。',
      regimen: [
        {
          group: '呼吸道',
          name: 'ACTEIN 600mg',
          sources: ['M1'],
        },
        {
          group: '認知／情緒與鎮靜',
          name: 'Aricept、Imimine、Rivotril',
          sources: ['M2', 'M3', 'M21'],
        },
        {
          group: '泌尿系統用藥',
          name: 'Harnalidge',
          sources: ['M4'],
        },
        {
          group: '泌尿系統用藥',
          name: 'Oxbu',
          sources: ['M5'],
        },
        {
          group: '泌尿系統用藥',
          name: 'Betmiga',
          sources: ['M6'],
        },
        {
          group: '眼科',
          name: 'PATEAR、Brimonin、Xalatan、Cosopt',
          sources: ['M7', 'M8', 'M9', 'M10'],
        },
        {
          group: '血糖／腎臟',
          name: 'Forxiga 10mg',
          sources: ['M15'],
        },
        {
          group: '甲狀腺／尿酸／葉酸',
          name: 'Eltroxin、Feburic、Folacin',
          sources: ['M12', 'M13', 'M14'],
        },
        {
          group: '腸胃道',
          name: 'Kascoal、Domperidone、Famotidine、Mosapride',
          sources: ['M16', 'M18', 'M19', 'M20'],
        },
        {
          group: '排便',
          name: 'Sennosides',
          sources: ['M11', 'M17'],
        },
      ],
      changes: [],
      reconciliation: [
        {
          reason: 'multi-facility',
          text: 'Sennosides於2026-07-20與07-21分別出現在示範嘉恩醫院及示範向陽藥局紀錄；可能是處方與調劑流程，也可能同時持有，需以藥袋確認實際來源與服法。',
          sources: ['M11', 'M17'],
        },
      ],
    },
    problems: [
      { label: '慢性腎臟病第3b期', basis: '照護計畫及eGFR 32–33 mL/min/1.73m²', kind: 'careplan', sources: ['K1', 'K2', 'O7', 'O18'] },
      { label: '多發性骨髓瘤（申報診斷）', basis: '2026-06至08月多次門診申報，需回原病歷確認', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: '肺炎（申報診斷）', basis: '2026-06至08月多次門診申報', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: '貧血', basis: 'Hb 11.2→12.1 g/dL，仍低於參考區間', kind: 'lab', sources: ['O9', 'O20'] },
      { label: '良性攝護腺增生', basis: '近期門診／調劑及排尿相關用藥', kind: 'diagnosis', sources: ['E3', 'E4', 'E10', 'E16', 'E22', 'M4'] },
      { label: '右側原發性隅角開放性青光眼', basis: '多次門診申報與眼藥水調劑', kind: 'diagnosis', sources: ['E5', 'E12', 'E17', 'E23', 'M8', 'M9'] },
      { label: '第二型糖尿病', basis: '出院病摘、HbA1c及用藥紀錄', kind: 'discharge', sources: ['D1', 'O10', 'M15'], documentEvidence: [{ source: 'D1', quote: 'Diebetes mellitus' }] },
      { label: '胃食道逆流', basis: '出院病摘與Famotidine紀錄', kind: 'discharge', sources: ['D1', 'M19'], documentEvidence: [{ source: 'D1', quote: 'Reflux esophagitis, L.A. grade A; Erythematous gastritis' }] },
      { label: '甲狀腺功能低下', basis: '出院病摘與Eltroxin紀錄', kind: 'discharge', sources: ['D1', 'M13'], documentEvidence: [{ source: 'D1', quote: 'Hypothyrodism, under Levothyroxine' }] },
      { label: '高血脂症', basis: '出院病摘既往病史', kind: 'discharge', sources: ['D1'], documentEvidence: [{ source: 'D1', quote: 'Hyperlipidemia' }] },
      { label: '高尿酸血症／痛風治療中（推定）', basis: 'Feburic持續調劑，資料未列尿酸值', kind: 'medication', sources: ['M14'] },
      { label: '脂肪肝、膽囊沉積物與腎結石', basis: '2026-02-05腹部超音波', kind: 'other', sources: ['L27'] },
      { label: '譫妄（申報診斷）', basis: '2026-07及08月就醫申報', kind: 'diagnosis', sources: ['E2', 'E9'] },
    ],
    // Follow-up and safety actions live in the separate safety analysis.
    decisions: [],
    // Keep the objective milestones identical to the patient view; only the
    // wording differs by audience.
    timeline: [
      { ref: 'K1', label: '啟用末期腎臟病前期 (Pre-ESRD) 照護計畫', category: 'followup' },
      { ref: 'D1', label: '因含血嘔吐／疑似上消化道出血住院評估', category: 'encounter', documentEvidence: [{ source: 'D1', quote: 'vomiting with some blood today' }] },
      { ref: 'L28', label: '腦部無對比電腦斷層檢查', category: 'procedure' },
      { ref: 'L27', label: '腹部超音波：脂肪肝、膽囊沉積物與腎結石', category: 'procedure' },
      { ref: 'L26', label: '心電圖檢查', category: 'lab' },
      { ref: 'L15', label: '胸部X光：雙下肺病灶與雙側肋膜積液', category: 'lab' },
      { ref: 'E1', label: '最新門診申報含肺炎、血液疾病與貧血診斷碼', category: 'encounter' },
    ],
  },
  patient: {
    headline: '您的腎功能需要持續追蹤；近期門診申報也重複出現肺炎與血液疾病診斷碼，建議向原看診醫師確認。',
    summary: [
      { text: '健康紀錄顯示您持續追蹤', emphasis: false, sources: [] },
      { text: '慢性腎臟病與攝護腺問題', emphasis: true, sources: ['K1', 'K2', 'E3', 'E4'] },
      { text: '。2026-05-25至06-02的', emphasis: false, sources: [] },
      { text: 'eGFR由33降至32', emphasis: true, sources: ['O7', 'O18'] },
      { text: '，血色素由11.2升至12.1 g/dL但仍低於報告參考值。', emphasis: false, sources: ['O9', 'O20'] },
      { text: '2026-06至08月的門診申報多次列有', emphasis: false, sources: [] },
      { text: '肺炎、多發性骨髓瘤與貧血', emphasis: true, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: '。申報碼不是完整診斷報告，請在回診時確認哪些診斷已由醫師正式確認，以及目前是否需要相關追蹤。', emphasis: false, sources: ['E1', 'E6', 'E13', 'E19'] },
    ],
    investigations: [
      {
        label: '腎功能（Creatinine／eGFR）',
        kind: 'lab',
        direction: 'worsening',
        trend: 'Creatinine 1.88→1.93 mg/dL；eGFR 33→32 mL/min/1.73m²',
        interpretation: '8天內有小幅變化；請依原醫療團隊安排持續追蹤，不要自行調整藥物。',
        sources: ['O6', 'O7', 'O17', 'O18'],
      },
      {
        label: '貧血相關數值',
        kind: 'lab',
        direction: 'improving',
        trend: '血色素11.2→12.1 g/dL；血比容35.8→37.2%',
        interpretation: '數值有回升，但血色素仍低於檢驗單參考值，可請醫師說明原因與後續追蹤。',
        sources: ['O8', 'O9', 'O19', 'O20'],
      },
      {
        label: '血糖相關數值',
        kind: 'lab',
        direction: 'stable',
        trend: '糖化血色素6.6%；餐後血糖126→124 mg/dL',
        interpretation: '兩次餐後血糖接近；糖化血色素只有一筆，請由醫師依您的年齡與整體狀況設定目標。',
        sources: ['O10', 'O14', 'O23'],
      },
      {
        label: '胸部影像',
        kind: 'imaging',
        direction: 'single',
        trend: '支氣管周圍浸潤、雙下肺斑片狀病灶與雙側肋膜積液',
        interpretation: '這是最新一次影像的文字結果，原因仍要由醫師配合當時症狀與其他檢查判斷。',
        sources: ['L15'],
      },
    ],
    medicationEducation: [
      {
        name: 'Forxiga（達格列淨）',
        benefit: '這筆處方的紀錄原因是慢性腎臟病第3b期；此藥也常用於血糖與腎臟照護。',
        attention: '請依醫囑使用；若有明顯脫水、無法進食、手術安排或泌尿／生殖器不適，請先聯絡醫療團隊。',
        sources: ['M15'],
      },
      {
        name: 'Harnalidge（tamsulosin）',
        benefit: '紀錄顯示這是泌尿系統用藥，用於協助改善攝護腺相關排尿症狀。',
        attention: '若起身時明顯頭暈，請放慢動作並告知醫師；不要自行停藥。',
        sources: ['M4'],
      },
      {
        name: 'Oxbu（oxybutynin）',
        benefit: '紀錄顯示這是泌尿系統用藥，用於協助改善膀胱相關排尿症狀。',
        attention: '若出現明顯口乾、便祕、排尿困難或意識混亂，請告知醫師；不要自行停藥。',
        sources: ['M5'],
      },
      {
        name: 'Betmiga（mirabegron）',
        benefit: '紀錄顯示這是泌尿系統用藥，用於協助改善膀胱相關排尿症狀；它不是抗膽鹼藥。',
        attention: '請依醫囑使用；實際用途與個別注意事項可向醫師或藥師確認。',
        sources: ['M6'],
      },
      {
        name: '青光眼眼藥水（Brimonin、Xalatan、Cosopt）',
        benefit: '這些眼藥水用於協助控制眼壓。',
        attention: '請依眼科指示點藥；多種眼藥水的順序與間隔不確定時，可請醫師或藥師示範。',
        sources: ['M8', 'M9', 'M10'],
      },
    ],
    medicationReview: {
      regimen: [],
      changes: [],
      reconciliation: [],
    },
    problems: [
      { label: '慢性腎臟病第3b期', basis: '照護計畫與腎功能檢驗', kind: 'careplan', sources: ['K1', 'K2', 'O7', 'O18'] },
      { label: '多發性骨髓瘤（申報紀錄）', basis: '2026-06至08月多次門診申報，需向原醫師確認', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: '肺炎（申報紀錄）', basis: '2026-06至08月多次門診申報', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: '貧血', basis: '血色素仍低於檢驗單參考值', kind: 'lab', sources: ['O9', 'O20'] },
      { label: '良性攝護腺增生', basis: '近期門診／調劑與排尿相關用藥', kind: 'diagnosis', sources: ['E3', 'E4', 'E10', 'E16', 'E22', 'M4'] },
      { label: '右側原發性隅角開放性青光眼', basis: '多次門診申報與眼藥水調劑', kind: 'diagnosis', sources: ['E5', 'E12', 'E17', 'E23', 'M8', 'M9'] },
      { label: '第二型糖尿病', basis: '出院病摘與血糖相關檢驗', kind: 'discharge', sources: ['D1', 'O10'], documentEvidence: [{ source: 'D1', quote: 'Diebetes mellitus' }] },
      { label: '胃食道逆流', basis: '出院病摘紀錄', kind: 'discharge', sources: ['D1'], documentEvidence: [{ source: 'D1', quote: 'Reflux esophagitis, L.A. grade A; Erythematous gastritis' }] },
      { label: '甲狀腺功能低下', basis: '出院病摘與甲狀腺素處方', kind: 'discharge', sources: ['D1', 'M13'], documentEvidence: [{ source: 'D1', quote: 'Hypothyrodism, under Levothyroxine' }] },
      { label: '脂肪肝、膽囊沉積物與腎結石', basis: '腹部超音波紀錄', kind: 'other', sources: ['L27'] },
      { label: '譫妄（申報紀錄）', basis: '2026-07及08月就醫申報', kind: 'diagnosis', sources: ['E2', 'E9'] },
    ],
    // Follow-up and safety actions live in the separate safety analysis.
    decisions: [],
    // Same refs and categories as the clinician view; wording is plainer.
    timeline: [
      { ref: 'K1', label: '開始腎臟照護計畫', category: 'followup' },
      { ref: 'D1', label: '因嘔吐物帶血住院檢查', category: 'encounter', documentEvidence: [{ source: 'D1', quote: 'vomiting with some blood today' }] },
      { ref: 'L28', label: '接受腦部電腦斷層檢查', category: 'procedure' },
      { ref: 'L27', label: '腹部超音波檢查', category: 'procedure' },
      { ref: 'L26', label: '心電圖檢查', category: 'lab' },
      { ref: 'L15', label: '胸部X光檢查', category: 'lab' },
      { ref: 'E1', label: '8月12日最新門診申報', category: 'encounter' },
    ],
  },
}

const demoMedicalSummarySnapshotsEn: Record<Audience, MedicalSummaryAiResult> = {
  medical: {
    headline: '94-year-old man with stage 3b chronic kidney disease and anemia; recent claims repeatedly include pneumonia and hematologic-disease diagnosis codes.',
    summary: [
      { text: 'This 94-year-old man is enrolled in a ', emphasis: false, sources: [] },
      { text: 'chronic kidney disease care plan', emphasis: true, sources: ['K1', 'K2'] },
      { text: '. From 2026-05-25 to 06-02, renal indices changed from ', emphasis: false, sources: [] },
      { text: 'creatinine 1.88→1.93 mg/dL and eGFR 33→32 mL/min/1.73m²', emphasis: true, sources: ['O6', 'O7', 'O17', 'O18'] },
      { text: '. Multiple outpatient claims from June through August 2026 listed ', emphasis: false, sources: [] },
      { text: 'pneumonia, multiple myeloma, and anemia', emphasis: true, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: '; these are claims diagnoses, so the source records should be reviewed to confirm the diagnoses, stage, and treatment status. ', emphasis: false, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: 'A 2026-06-02 chest radiograph also described peribronchial infiltration, patchy bilateral lower-lung opacities, bilateral pleural changes with effusions, and borderline cardiomegaly.', emphasis: false, sources: ['L15'] },
    ],
    investigations: [
      {
        label: 'Renal function (creatinine/eGFR)',
        kind: 'lab',
        direction: 'worsening',
        trend: 'Creatinine 1.88→1.93 mg/dL; eGFR 33→32 mL/min/1.73m²',
        interpretation: 'Renal indices declined slightly over eight days; the established stage 3b chronic kidney disease should continue to be followed longitudinally.',
        sources: ['O6', 'O7', 'O17', 'O18'],
      },
      {
        label: 'Anemia indices (Hb/HCT)',
        kind: 'lab',
        direction: 'improving',
        trend: 'Hb 11.2→12.1 g/dL; HCT 35.8→37.2%',
        interpretation: 'Both values improved, but hemoglobin remains below the reported reference interval of 13.5–17.5 g/dL.',
        sources: ['O8', 'O9', 'O19', 'O20'],
      },
      {
        label: 'Glycemic indices (HbA1c/postprandial glucose)',
        kind: 'lab',
        direction: 'stable',
        trend: 'HbA1c 6.6%; postprandial glucose 126→124 mg/dL',
        interpretation: 'The two postprandial glucose values are similar. Only one HbA1c result is available, so it should be interpreted against an individualized target.',
        sources: ['O10', 'O14', 'O23'],
      },
      {
        label: 'Chest imaging',
        kind: 'imaging',
        direction: 'single',
        trend: 'Peribronchial infiltration, patchy bilateral lower-lung opacities, and bilateral pleural effusions',
        interpretation: 'This reflects the most recent imaging report only; no cause or longitudinal change is inferred from this single study.',
        sources: ['L15'],
      },
    ],
    medicationEducation: [],
    medicationReview: {
      overview: 'Records from July and August 2026 include respiratory, cognitive/mood, urinary, ophthalmic, renal/metabolic, thyroid/urate, and gastrointestinal medications. Reconcile the active list against the patient’s actual medication packages across facilities.',
      regimen: [
        { group: 'Respiratory', name: 'ACTEIN 600mg', sources: ['M1'] },
        { group: 'Cognition/mood and sedation', name: 'Aricept, Imimine, Rivotril', sources: ['M2', 'M3', 'M21'] },
        { group: 'Urinary medication', name: 'Harnalidge', sources: ['M4'] },
        { group: 'Urinary medication', name: 'Oxbu', sources: ['M5'] },
        { group: 'Urinary medication', name: 'Betmiga', sources: ['M6'] },
        { group: 'Ophthalmic', name: 'PATEAR, Brimonin, Xalatan, Cosopt', sources: ['M7', 'M8', 'M9', 'M10'] },
        { group: 'Glucose/renal', name: 'Forxiga 10mg', sources: ['M15'] },
        { group: 'Thyroid/urate/folate', name: 'Eltroxin, Feburic, Folacin', sources: ['M12', 'M13', 'M14'] },
        { group: 'Gastrointestinal', name: 'Kascoal, Domperidone, Famotidine, Mosapride', sources: ['M16', 'M18', 'M19', 'M20'] },
        { group: 'Bowel regimen', name: 'Sennosides', sources: ['M11', 'M17'] },
      ],
      changes: [],
      reconciliation: [
        {
          reason: 'multi-facility',
          text: 'Sennosides appears in records from Demo Grace Hospital on 2026-07-20 and Demo Sunny Pharmacy on 2026-07-21. This may reflect prescribing and dispensing, or concurrent supplies; verify the actual source and directions from the medication packages.',
          sources: ['M11', 'M17'],
        },
      ],
    },
    problems: [
      { label: 'Stage 3b chronic kidney disease', basis: 'Care plans and eGFR 32–33 mL/min/1.73m²', kind: 'careplan', sources: ['K1', 'K2', 'O7', 'O18'] },
      { label: 'Multiple myeloma (claims diagnosis)', basis: 'Repeated outpatient claims from June through August 2026; confirm in the source record', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: 'Pneumonia (claims diagnosis)', basis: 'Repeated outpatient claims from June through August 2026', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: 'Anemia', basis: 'Hb 11.2→12.1 g/dL, still below the reported reference interval', kind: 'lab', sources: ['O9', 'O20'] },
      { label: 'Benign prostatic hyperplasia', basis: 'Recent encounters, dispensing records, and urinary medication', kind: 'diagnosis', sources: ['E3', 'E4', 'E10', 'E16', 'E22', 'M4'] },
      { label: 'Primary open-angle glaucoma, right eye', basis: 'Repeated claims and ophthalmic medication dispensing', kind: 'diagnosis', sources: ['E5', 'E12', 'E17', 'E23', 'M8', 'M9'] },
      { label: 'Type 2 diabetes mellitus', basis: 'Discharge summary, HbA1c, and medication records', kind: 'discharge', sources: ['D1', 'O10', 'M15'], documentEvidence: [{ source: 'D1', quote: 'Diebetes mellitus' }] },
      { label: 'Gastroesophageal reflux disease', basis: 'Discharge summary and famotidine record', kind: 'discharge', sources: ['D1', 'M19'], documentEvidence: [{ source: 'D1', quote: 'Reflux esophagitis, L.A. grade A; Erythematous gastritis' }] },
      { label: 'Hypothyroidism', basis: 'Discharge summary and Eltroxin record', kind: 'discharge', sources: ['D1', 'M13'], documentEvidence: [{ source: 'D1', quote: 'Hypothyrodism, under Levothyroxine' }] },
      { label: 'Hyperlipidemia', basis: 'Past history in the discharge summary', kind: 'discharge', sources: ['D1'], documentEvidence: [{ source: 'D1', quote: 'Hyperlipidemia' }] },
      { label: 'Hyperuricemia/gout under treatment (inferred)', basis: 'Ongoing Feburic dispensing; no uric-acid value is included', kind: 'medication', sources: ['M14'] },
      { label: 'Fatty liver, gallbladder sludge, and renal stones', basis: 'Abdominal ultrasound on 2026-02-05', kind: 'other', sources: ['L27'] },
      { label: 'Delirium (claims diagnosis)', basis: 'Claims from July and August 2026', kind: 'diagnosis', sources: ['E2', 'E9'] },
    ],
    decisions: [],
    timeline: [
      { ref: 'K1', label: 'Pre-ESRD care plan initiated', category: 'followup' },
      { ref: 'D1', label: 'Hospital evaluation for bloody emesis/possible upper gastrointestinal bleeding', category: 'encounter', documentEvidence: [{ source: 'D1', quote: 'vomiting with some blood today' }] },
      { ref: 'L28', label: 'Non-contrast brain CT', category: 'procedure' },
      { ref: 'L27', label: 'Abdominal ultrasound: fatty liver, gallbladder sludge, and renal stones', category: 'procedure' },
      { ref: 'L26', label: 'Electrocardiogram', category: 'lab' },
      { ref: 'L15', label: 'Chest radiograph: bilateral lower-lung findings and bilateral pleural effusions', category: 'lab' },
      { ref: 'E1', label: 'Latest outpatient claim includes pneumonia, hematologic-disease, and anemia codes', category: 'encounter' },
    ],
  },
  patient: {
    headline: 'Your kidney function needs continued follow-up. Recent outpatient claims also repeatedly include pneumonia and blood-disorder codes that should be confirmed with the treating clinician.',
    summary: [
      { text: 'Your health records show ongoing follow-up for ', emphasis: false, sources: [] },
      { text: 'chronic kidney disease and prostate-related urinary problems', emphasis: true, sources: ['K1', 'K2', 'E3', 'E4'] },
      { text: '. From 2026-05-25 to 06-02, ', emphasis: false, sources: [] },
      { text: 'eGFR decreased from 33 to 32', emphasis: true, sources: ['O7', 'O18'] },
      { text: ', while hemoglobin increased from 11.2 to 12.1 g/dL but remained below the report’s reference range. ', emphasis: false, sources: ['O9', 'O20'] },
      { text: 'Outpatient claims from June through August 2026 repeatedly listed ', emphasis: false, sources: [] },
      { text: 'pneumonia, multiple myeloma, and anemia', emphasis: true, sources: ['E1', 'E6', 'E13', 'E19'] },
      { text: '. Claims codes are not complete diagnostic reports; ask the treating clinician which diagnoses are confirmed and what follow-up is currently needed.', emphasis: false, sources: ['E1', 'E6', 'E13', 'E19'] },
    ],
    investigations: [
      {
        label: 'Kidney function (creatinine/eGFR)',
        kind: 'lab',
        direction: 'worsening',
        trend: 'Creatinine 1.88→1.93 mg/dL; eGFR 33→32 mL/min/1.73m²',
        interpretation: 'The values changed slightly over eight days. Continue follow-up as arranged by your care team and do not change medications on your own.',
        sources: ['O6', 'O7', 'O17', 'O18'],
      },
      {
        label: 'Anemia-related values',
        kind: 'lab',
        direction: 'improving',
        trend: 'Hemoglobin 11.2→12.1 g/dL; hematocrit 35.8→37.2%',
        interpretation: 'The values improved, but hemoglobin remains below the laboratory report’s reference range. Ask your clinician about the cause and follow-up plan.',
        sources: ['O8', 'O9', 'O19', 'O20'],
      },
      {
        label: 'Blood glucose-related values',
        kind: 'lab',
        direction: 'stable',
        trend: 'HbA1c 6.6%; postprandial glucose 126→124 mg/dL',
        interpretation: 'The two postprandial glucose values are similar. Only one HbA1c result is available, so your clinician should set a target based on your age and overall health.',
        sources: ['O10', 'O14', 'O23'],
      },
      {
        label: 'Chest imaging',
        kind: 'imaging',
        direction: 'single',
        trend: 'Peribronchial infiltration, patchy bilateral lower-lung opacities, and bilateral pleural effusions',
        interpretation: 'This is the wording from the latest imaging report. Your clinician needs to interpret the cause together with symptoms and other tests from that visit.',
        sources: ['L15'],
      },
    ],
    medicationEducation: [
      {
        name: 'Forxiga (dapagliflozin)',
        benefit: 'This prescription was recorded for stage 3b chronic kidney disease. This medication is also commonly used in glucose and kidney care.',
        attention: 'Use it as prescribed. Contact your care team first if you have significant dehydration, cannot eat, have planned surgery, or develop urinary/genital symptoms.',
        sources: ['M15'],
      },
      {
        name: 'Harnalidge (tamsulosin)',
        benefit: 'The record identifies this as a urinary medication used to help prostate-related urinary symptoms.',
        attention: 'If you feel markedly dizzy when standing, rise slowly and tell your clinician. Do not stop it on your own.',
        sources: ['M4'],
      },
      {
        name: 'Oxbu (oxybutynin)',
        benefit: 'The record identifies this as a urinary medication used to help bladder-related urinary symptoms.',
        attention: 'Tell your clinician about marked dry mouth, constipation, difficulty urinating, or confusion. Do not stop it on your own.',
        sources: ['M5'],
      },
      {
        name: 'Betmiga (mirabegron)',
        benefit: 'The record identifies this as a urinary medication used to help bladder-related urinary symptoms; it is not an anticholinergic medication.',
        attention: 'Use it as prescribed. Ask your clinician or pharmacist to confirm its purpose and individualized precautions.',
        sources: ['M6'],
      },
      {
        name: 'Glaucoma eye drops (Brimonin, Xalatan, Cosopt)',
        benefit: 'These eye drops are used to help control eye pressure.',
        attention: 'Use them as directed by ophthalmology. If you are unsure about the order or spacing of several drops, ask a clinician or pharmacist to demonstrate.',
        sources: ['M8', 'M9', 'M10'],
      },
    ],
    medicationReview: { regimen: [], changes: [], reconciliation: [] },
    problems: [
      { label: 'Stage 3b chronic kidney disease', basis: 'Care plans and kidney-function tests', kind: 'careplan', sources: ['K1', 'K2', 'O7', 'O18'] },
      { label: 'Multiple myeloma (claims record)', basis: 'Repeated outpatient claims from June through August 2026; confirm with the treating clinician', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: 'Pneumonia (claims record)', basis: 'Repeated outpatient claims from June through August 2026', kind: 'diagnosis', sources: ['E1', 'E6', 'E13', 'E19'] },
      { label: 'Anemia', basis: 'Hemoglobin remains below the laboratory report’s reference range', kind: 'lab', sources: ['O9', 'O20'] },
      { label: 'Benign prostatic hyperplasia', basis: 'Recent encounters, dispensing records, and urinary medication', kind: 'diagnosis', sources: ['E3', 'E4', 'E10', 'E16', 'E22', 'M4'] },
      { label: 'Primary open-angle glaucoma, right eye', basis: 'Repeated claims and eye-drop dispensing', kind: 'diagnosis', sources: ['E5', 'E12', 'E17', 'E23', 'M8', 'M9'] },
      { label: 'Type 2 diabetes mellitus', basis: 'Discharge summary and glucose-related tests', kind: 'discharge', sources: ['D1', 'O10'], documentEvidence: [{ source: 'D1', quote: 'Diebetes mellitus' }] },
      { label: 'Gastroesophageal reflux disease', basis: 'Discharge summary', kind: 'discharge', sources: ['D1'], documentEvidence: [{ source: 'D1', quote: 'Reflux esophagitis, L.A. grade A; Erythematous gastritis' }] },
      { label: 'Hypothyroidism', basis: 'Discharge summary and thyroid-hormone prescription', kind: 'discharge', sources: ['D1', 'M13'], documentEvidence: [{ source: 'D1', quote: 'Hypothyrodism, under Levothyroxine' }] },
      { label: 'Fatty liver, gallbladder sludge, and renal stones', basis: 'Abdominal ultrasound record', kind: 'other', sources: ['L27'] },
      { label: 'Delirium (claims record)', basis: 'Claims from July and August 2026', kind: 'diagnosis', sources: ['E2', 'E9'] },
    ],
    decisions: [],
    timeline: [
      { ref: 'K1', label: 'Kidney care plan initiated', category: 'followup' },
      { ref: 'D1', label: 'Hospital evaluation for bloody vomit', category: 'encounter', documentEvidence: [{ source: 'D1', quote: 'vomiting with some blood today' }] },
      { ref: 'L28', label: 'Brain CT performed', category: 'procedure' },
      { ref: 'L27', label: 'Abdominal ultrasound performed', category: 'procedure' },
      { ref: 'L26', label: 'Electrocardiogram performed', category: 'lab' },
      { ref: 'L15', label: 'Chest radiograph performed', category: 'lab' },
      { ref: 'E1', label: 'Latest outpatient claim on August 12', category: 'encounter' },
    ],
  },
}

export const demoMedicalSummarySnapshots: Record<SnapshotLocale, Record<Audience, MedicalSummaryAiResult>> = {
  'zh-TW': demoMedicalSummarySnapshotsZhTw,
  en: demoMedicalSummarySnapshotsEn,
}

const demoSafetyScanSnapshotsZhTw: Record<Audience, SafetyScanResultInput> = {
  medical: {
    scannedCount: 97,
    alerts: [
      {
        severity: 'medium',
        title: '抗膽鹼與認知風險需整合評估',
        detail: '94歲患者近期同時有Aricept、Imimine與Oxbu紀錄；Imipramine及oxybutynin具抗膽鹼作用，Oxbu在使用膽鹼酯酶抑制劑的失智患者需特別謹慎。Betmiga為β3腎上腺素受體促效劑，不列入抗膽鹼藥。',
        evidence: [
          'ARICEPT F.C. TABLETS 5MG',
          'IMIMINE S.C. TABLETS 25MG',
          'Oxbu Extended-release Tablets 5mg',
        ],
        sources: ['M2', 'M3', 'M5'],
        category: 'other',
        recommendation: '核對實際服用狀況與適應症，評估認知變化、譫妄、口乾、便祕及尿滯留；調整須由醫師或藥師完成。',
      },
      {
        severity: 'medium',
        title: '腎功能趨勢與現行用藥追蹤',
        detail: '2026-05-25至06-02 Creatinine由1.88升至1.93 mg/dL、eGFR由33降至32 mL/min/1.73m²；現有Forxiga與Feburic紀錄，應依實際適應症、體液狀態及後續數值定期檢視，但不能僅由eGFR 32判定需要停藥或調整劑量。',
        evidence: [
          'Creatinine 1.88→1.93 mg/dL',
          'eGFR 33→32 mL/min/1.73m²',
          'Forxiga 10mg；Feburic 80mg',
        ],
        sources: ['O6', 'O7', 'O17', 'O18', 'M14', 'M15'],
        category: 'renal',
        recommendation: '持續追蹤腎功能、體液狀態與相關檢驗，並於藥物整合時確認每項藥物的適應症及劑量。',
      },
      {
        severity: 'medium',
        title: '重大申報診斷需回原病歷確認',
        detail: '2026-06至08月多次門診申報同時出現肺炎、多發性骨髓瘤未達緩解及貧血診斷碼；目前選取資料未提供病理、分期或治療細節，不能只靠申報碼判定疾病狀態。',
        evidence: ['2026-06-03、07-01、07-22、08-12重複申報'],
        sources: ['E1', 'E6', 'E13', 'E19'],
        category: 'monitoring',
        recommendation: '向原看診院所核對診斷依據、目前分期／緩解狀態及追蹤計畫，再決定摘要中的正式問題清單。',
      },
    ],
  },
  patient: {
    scannedCount: 97,
    alerts: [
      {
        severity: 'medium',
        title: '腎功能需要持續追蹤',
        detail: '2026-05-25至06-02的肌酸酐由1.88升至1.93 mg/dL，eGFR由33降至32 mL/min/1.73m²，代表這段期間腎功能數值有小幅變化。',
        evidence: [
          'Creatinine 1.88→1.93 mg/dL',
          'eGFR 33→32 mL/min/1.73m²',
        ],
        sources: ['O6', 'O7', 'O17', 'O18'],
        category: 'renal',
        recommendation: '請依原醫療團隊安排回診與抽血，並攜帶完整藥袋；不要只依單次數值自行停藥或改劑量。',
      },
      {
        severity: 'medium',
        title: '部分藥物可能影響警覺與排便',
        detail: '近期紀錄中有Imimine與Oxbu；Imimine與Oxbu都可能有抗膽鹼作用。高齡者若出現明顯意識混亂、嗜睡、口乾、便祕或排尿困難，應讓醫療團隊知道。Betmiga不是抗膽鹼藥。',
        evidence: ['IMIMINE S.C. TABLETS 25MG', 'Oxbu Extended-release Tablets 5mg'],
        sources: ['M3', 'M5'],
        category: 'other',
        recommendation: '下次回診請攜帶所有藥袋並說明實際服法；若出現意識混亂、嗜睡、口乾、便祕或排尿困難，請儘早聯絡醫療團隊，不要自行停藥。',
      },
      {
        severity: 'medium',
        title: '請確認申報紀錄中的重大診斷',
        detail: '2026-06至08月的門診申報多次出現肺炎、多發性骨髓瘤及貧血代碼；申報碼不是完整診斷報告，這份資料也沒有病理、分期或治療細節。',
        evidence: ['2026-06-03、07-01、07-22、08-12重複申報'],
        sources: ['E1', 'E6', 'E13', 'E19'],
        category: 'monitoring',
        recommendation: '請向原看診醫師確認哪些診斷已正式確立、目前狀態及下一步追蹤；若有發燒、喘或其他急性不適，請及時就醫。',
      },
    ],
  },
}

const demoSafetyScanSnapshotsEn: Record<Audience, SafetyScanResultInput> = {
  medical: {
    scannedCount: 97,
    alerts: [
      {
        severity: 'medium',
        title: 'Review combined anticholinergic and cognitive risk',
        detail: 'Recent records include Aricept, Imimine, and Oxbu in this 94-year-old patient. Imipramine and oxybutynin have anticholinergic effects, and Oxbu warrants particular caution in a patient with dementia who is receiving a cholinesterase inhibitor. Betmiga is a beta-3 adrenergic agonist and is not classified as an anticholinergic medication.',
        evidence: [
          'ARICEPT F.C. TABLETS 5MG',
          'IMIMINE S.C. TABLETS 25MG',
          'Oxbu Extended-release Tablets 5mg',
        ],
        sources: ['M2', 'M3', 'M5'],
        category: 'other',
        recommendation: 'Reconcile actual use and indications, and assess cognition, delirium, dry mouth, constipation, and urinary retention. Medication changes should be made by a clinician or pharmacist.',
      },
      {
        severity: 'medium',
        title: 'Follow the renal trend alongside the current medication list',
        detail: 'From 2026-05-25 to 06-02, creatinine increased from 1.88 to 1.93 mg/dL and eGFR decreased from 33 to 32 mL/min/1.73m². Forxiga and Feburic are present in the medication records. Review them periodically against the actual indications, volume status, and subsequent laboratory values; eGFR 32 alone is not enough to conclude that either medication must be stopped or dose-adjusted.',
        evidence: [
          'Creatinine 1.88→1.93 mg/dL',
          'eGFR 33→32 mL/min/1.73m²',
          'Forxiga 10mg; Feburic 80mg',
        ],
        sources: ['O6', 'O7', 'O17', 'O18', 'M14', 'M15'],
        category: 'renal',
        recommendation: 'Continue to monitor renal function, volume status, and relevant laboratory values, and confirm each medication’s indication and dose during medication reconciliation.',
      },
      {
        severity: 'medium',
        title: 'Confirm major claims diagnoses in the source medical record',
        detail: 'Multiple outpatient claims from June through August 2026 include diagnosis codes for pneumonia, multiple myeloma not in remission, and anemia. The selected data do not provide pathology, staging, or treatment details, so disease status cannot be established from claims codes alone.',
        evidence: ['Repeated claims on 2026-06-03, 07-01, 07-22, and 08-12'],
        sources: ['E1', 'E6', 'E13', 'E19'],
        category: 'monitoring',
        recommendation: 'Verify the diagnostic basis, current stage/remission status, and follow-up plan with the treating facility before placing these diagnoses on the confirmed problem list.',
      },
    ],
  },
  patient: {
    scannedCount: 97,
    alerts: [
      {
        severity: 'medium',
        title: 'Your kidney function needs continued follow-up',
        detail: 'From 2026-05-25 to 06-02, creatinine increased from 1.88 to 1.93 mg/dL and eGFR decreased from 33 to 32 mL/min/1.73m², showing a small change in kidney-function values during that period.',
        evidence: [
          'Creatinine 1.88→1.93 mg/dL',
          'eGFR 33→32 mL/min/1.73m²',
        ],
        sources: ['O6', 'O7', 'O17', 'O18'],
        category: 'renal',
        recommendation: 'Attend follow-up visits and blood tests as arranged, and bring all medication packages. Do not stop or change a dose based on a single value without speaking with your care team.',
      },
      {
        severity: 'medium',
        title: 'Some medications may affect alertness and bowel function',
        detail: 'Recent records include Imimine and Oxbu, both of which may have anticholinergic effects. In an older adult, marked confusion, drowsiness, dry mouth, constipation, or difficulty urinating should be reported to the care team. Betmiga is not an anticholinergic medication.',
        evidence: ['IMIMINE S.C. TABLETS 25MG', 'Oxbu Extended-release Tablets 5mg'],
        sources: ['M3', 'M5'],
        category: 'other',
        recommendation: 'Bring all medication packages to the next visit and explain how you actually take each medicine. Contact the care team promptly for confusion, drowsiness, dry mouth, constipation, or difficulty urinating; do not stop medication on your own.',
      },
      {
        severity: 'medium',
        title: 'Confirm the major diagnoses listed in claims records',
        detail: 'Outpatient claims from June through August 2026 repeatedly include codes for pneumonia, multiple myeloma, and anemia. Claims codes are not complete diagnostic reports, and these data do not include pathology, staging, or treatment details.',
        evidence: ['Repeated claims on 2026-06-03, 07-01, 07-22, and 08-12'],
        sources: ['E1', 'E6', 'E13', 'E19'],
        category: 'monitoring',
        recommendation: 'Ask the treating clinician which diagnoses are confirmed, their current status, and the next follow-up step. Seek timely care for fever, shortness of breath, or other acute symptoms.',
      },
    ],
  },
}

export const demoSafetyScanSnapshots: Record<SnapshotLocale, Record<Audience, SafetyScanResultInput>> = {
  'zh-TW': demoSafetyScanSnapshotsZhTw,
  en: demoSafetyScanSnapshotsEn,
}
