// Pre-generated AI snapshots for the DEMO bundle (示範資料, demo-patient-1).
//
// Why: the demo bundle is frozen, so its AI output is effectively a constant —
// re-generating it for every first-time visitor burns two AI calls per visit
// (and the visitor's free-tier quota) to recompute a known answer, and exposes
// the first impression to transient model failures. These snapshots are REAL
// AI-authored raw outputs (same schema the live models produce), written
// against the catalog keys that buildSourceCatalog() derives from
// public/demo/demo-bundle.json.
//
// Provenance (2026-07-07): generated by gemini-3.1-flash-lite via the
// production proxy, using the app's real prompt builders and the default
// (newPatient) data selection. Each candidate run was audited (scripts + human)
// for citation relevance, evidence existence and trend faithfulness before
// being frozen here. The `investigations` rows were editorially backfilled on
// 2026-07-11 when that schema was introduced, using only the same audited
// report values/citations; live patients still use the model-generated path.
// Only the safety results are post-processed by the same
// filterDuplicateFalsePositives guard the live path applies.
//
// They deliberately store the RAW pre-parse shape, NOT the finalized result:
// the hooks feed them through the exact same parse → finalize/verify pipeline
// as a live reply, so citation resolution, verification marking and navigation
// stay honest. If the demo bundle ever changes, stale citations surface as
// amber "unverified" pills — the visible signal to regenerate this file (run
// scripts/validate-demo-snapshots.ts, or just re-author).
//
// Scope guards (enforced by the hooks): demo patient + zh-TW locale + no cached
// result. A retained model preference never causes an automatic live call;
// pressing 重新產生 explicitly still runs the selected model.
import type { MedicalSummaryAiResult } from '@/src/core/entities/medical-summary.entity'
import type { SafetyScanResultInput } from '@/src/core/entities/safety-alert.entity'

export const DEMO_PATIENT_ID = 'demo-patient-1'

type Audience = 'medical' | 'patient'

// Free-form custom-module snapshots are intentionally separate from the
// structured medical-summary snapshots. They preload only while the matching
// default prompt and default Insights model are still selected.
export const demoClinicalInsightSnapshots: Record<Audience, Record<string, { prompt: string; text: string }>> = {
  medical: {
    changes: {
      prompt: '比較病人最近的臨床資料與先前資訊，列出狀態、治療或結果中最重要的變化。強調需要注意的差異。',
      text: [
        '### 近期重要變化',
        '- **腎功能持續緩慢下降**：近期 eGFR 約由 35 降至 32 mL/min/1.73m²，應持續追蹤腎功能、蛋白尿與藥物劑量。',
        '- **心肺狀況需要追蹤**：近期胸部影像記錄雙側肺部浸潤、肋膜積水及輕度心臟擴大，需合併症狀與後續影像評估。',
        '- **貧血仍存在**：血色素約 11.2–12.1 g/dL，應配合慢性腎病與營養狀況一併判讀。',
        '- **近期反覆呼吸道就醫**：跨院紀錄中有肺炎、慢性咳嗽及住院事件，回診時宜確認症狀是否完全改善。',
      ].join('\n'),
    },
  },
  patient: {
    'health-overview': {
      prompt: '請用我匯入的個人健康資料，幫我整理一份白話版的健康總覽：目前的慢性病、正在使用的藥物，以及近期較需要關注的檢驗結果。專有名詞請在括號中簡單說明。最後提醒我若有疑慮應與醫師討論。',
      text: [
        '### 最近值得注意的健康變化',
        '- 腎功能數值最近有緩慢下降，需要按照醫師安排持續抽血追蹤。',
        '- 胸部檢查曾出現肺部浸潤與積水，若仍有喘、咳嗽或發燒，請儘早回診。',
        '- 血色素稍低，可能與慢性疾病等多種因素有關，可在下次看診時請醫師一起說明。',
        '',
        '這是依健康存摺資料整理的提醒，實際病情與用藥調整請和您的醫療團隊確認。',
      ].join('\n'),
    },
  },
}

/**
 * Return a bundled custom-insight snapshot solely from demo identity and panel
 * identity. Model preference is intentionally absent: retaining a model from a
 * real patient must never turn loading the frozen demo into an automatic cloud
 * request. Manual regeneration remains model-aware in the caller.
 */
export function getDemoClinicalInsightSnapshot(
  patientId: string,
  audience: Audience,
  panelId: string,
) {
  return patientId === DEMO_PATIENT_ID
    ? demoClinicalInsightSnapshots[audience][panelId]
    : undefined
}

export const demoMedicalSummarySnapshots: Record<Audience, MedicalSummaryAiResult> = {
  medical: {
    headline: '94歲男性，患有多重慢性疾病且腎功能持續監測中。',
    summary: [
      { text: '本病患為', emphasis: false, sources: [] },
      { text: '94歲高齡', emphasis: true, sources: [] },
      { text: '，近期因肺炎、慢性咳嗽及虛弱反覆就診。', emphasis: false, sources: ['E3', 'E9', 'E10', 'E11'] },
      { text: '腎功能指標呈現', emphasis: false, sources: [] },
      { text: 'eGFR 32', emphasis: true, sources: ['L7'] },
      { text: '之緩慢惡化趨勢，並伴有貧血及心臟相關追蹤紀錄。', emphasis: false, sources: ['L9', 'L16'] },
      { text: '近期胸部影像顯示雙側肺部浸潤與心臟輕微擴大，需注意肺部病灶與心臟功能。', emphasis: false, sources: ['L1'] },
    ],
    investigations: [
      {
        label: '腎功能（eGFR）',
        kind: 'lab',
        direction: 'worsening',
        trend: 'eGFR 35 → 33 → 32 mL/min/1.73m²',
        interpretation: '連續數值逐步下降，顯示慢性腎功能需持續監測。',
        sources: ['L7', 'L24'],
      },
      {
        label: '貧血指標',
        kind: 'lab',
        direction: 'fluctuating',
        trend: 'Hb 11.2–12.1 g/dL',
        interpretation: '血色素持續偏低且有波動，應合併腎臟病程與症狀追蹤。',
        sources: ['L9'],
      },
      {
        label: '胸部影像',
        kind: 'imaging',
        direction: 'single',
        trend: '單次最新結果：雙側肺部浸潤、雙側肋膜積水與輕微心臟擴大',
        interpretation: '目前只有一筆可比對的近期影像，無法單憑此筆判定長期趨勢。',
        sources: ['L1'],
      },
    ],
    medicationEducation: [],
    medicationReview: {
      regimen: [
        {
          group: '眼科',
          name: '青光眼局部用藥組合',
          sig: '近期紀錄包含派滴兒、Brimonidine、Latanoprost 與複方點眼液',
          sources: ['M3', 'M4', 'M5', 'M6'],
        },
        {
          group: '泌尿',
          name: 'Harnalidge OCAS 0.4 mg',
          sig: '近期紀錄平均每日 1 錠',
          sources: ['M19', 'M39'],
        },
        {
          group: '內分泌',
          name: 'Levothyroxine',
          sig: '近期紀錄平均每日 1 錠',
          sources: ['M15', 'M32'],
        },
        {
          group: '尿酸',
          name: 'Febuxostat 80 mg',
          sig: '近期紀錄平均每日 0.25 錠',
          sources: ['M16', 'M33'],
        },
      ],
      changes: [
        {
          type: 'new',
          medication: '青光眼局部用藥組合',
          summary: '四項眼科局部用藥集中出現在近期紀錄；此處僅代表紀錄中新出現，不等同本次開始使用。',
          sources: ['M3', 'M4', 'M5', 'M6'],
        },
        {
          type: 'cross-facility',
          medication: '便通樂膜衣錠',
          summary: '同一藥品於不同機構與日期的紀錄中出現，需於藥物整合時確認實際來源與用法。',
          sources: ['M8', 'M30'],
        },
      ],
      reconciliation: [
        {
          reason: 'uncertain-current',
          text: '青光眼點眼藥共列四項，需確認目前實際品項、點用頻率及是否仍全部使用。',
          sources: ['M3', 'M4', 'M5', 'M6'],
        },
        {
          reason: 'multi-facility',
          text: '便通樂膜衣錠有跨機構紀錄，需區分同次處方調劑與不同來源用藥。',
          sources: ['M8', 'M30'],
        },
      ],
    },
    problems: [
      { label: '慢性腎臟病', basis: '照護計畫及eGFR 32 ml/min/1.73m2', kind: 'diagnosis', sources: ['K1', 'K2', 'E4'] },
      { label: '肺炎', basis: '近期多次門診申報', kind: 'diagnosis', sources: ['E3', 'E9'] },
      { label: '青光眼', basis: '長期眼藥水處方', kind: 'diagnosis', sources: ['E2', 'E7', 'M3', 'M4', 'M5', 'M6'] },
      { label: '貧血', basis: '近期 Hb 11.2-12.1 g/dL', kind: 'lab', sources: ['L9'] },
      { label: '良性攝護腺增生', basis: '長期藥物治療', kind: 'diagnosis', sources: ['E6', 'E12', 'M19', 'M39'] },
      { label: '甲狀腺功能減退', basis: '持續性補充甲狀腺素', kind: 'medication', sources: ['M15', 'M32'] },
      { label: '高尿酸血症', basis: '長期使用降尿酸藥物', kind: 'medication', sources: ['M16', 'M33'] },
      { label: '胃及十二指腸息肉', basis: '門診申報紀錄', kind: 'diagnosis', sources: ['E5', 'E15', 'E18'] },
      { label: '脂肪肝', basis: '超音波檢查紀錄', kind: 'diagnosis', sources: ['L30'] },
      { label: '腎結石', basis: '超音波檢查紀錄', kind: 'diagnosis', sources: ['L30'] },
      { label: '膽囊沉積物', basis: '超音波檢查紀錄', kind: 'diagnosis', sources: ['L30'] },
    ],
    decisions: [
      { text: '密切追蹤肺部浸潤與肺炎症狀', urgency: 'high', rationale: '近期影像顯示雙側肺部浸潤及雙側肋膜積水', sources: ['L1'] },
      { text: '監測腎功能惡化趨勢', urgency: 'medium', rationale: 'eGFR由35降至32，需評估藥物對腎臟之影響', sources: ['L7'] },
      { text: '安排心臟超音波評估', urgency: 'medium', rationale: '心電圖顯示陳舊性前中隔梗塞及邊緣性心臟擴大', sources: ['L16', 'L1'] },
    ],
    // Timeline = the OBJECTIVE care journey: the SAME significant milestones as
    // the patient view (identical refs + categories), only the label wording
    // differs by audience. Curated (not per-audience AI-generated) because two
    // independent generations diverge in count/events — see the tightened
    // SHARED_RULES timeline rule that keeps live output close, plus this fixed
    // set for the frozen demo.
    timeline: [
      { ref: 'K1', label: '啟用末期腎臟病前期 (Pre-ESRD) 照護計畫', category: 'followup' },
      { ref: 'E21', label: 'COVID-19 重症住院', category: 'encounter' },
      { ref: 'E20', label: '肺炎住院治療', category: 'encounter' },
      { ref: 'E19', label: '因咳血住院檢查', category: 'encounter' },
      { ref: 'E16', label: '譫妄就診', category: 'diagnosis' },
      { ref: 'L30', label: '腹部超音波：脂肪肝、膽囊沉積物、腎結石', category: 'lab' },
      { ref: 'E3', label: '肺炎門診治療', category: 'diagnosis' },
    ],
  },
  patient: {
    headline: '這份紀錄呈現了您目前的定期追蹤與多項身體狀況，建議您於下次門診時與醫師討論報告細節。',
    summary: [
      { text: '您的健康存摺顯示，目前有多個科別的定期追蹤，', emphasis: false, sources: ['E2', 'E4', 'E5', 'E6'] },
      { text: '針對', emphasis: false, sources: [] },
      { text: '慢性腎臟病', emphasis: true, sources: ['E4', 'K1'] },
      { text: '與', emphasis: false, sources: [] },
      { text: '青光眼', emphasis: true, sources: ['E2', 'E7'] },
      { text: '等狀況，持續有相關藥物輔助治療與門診紀錄，醫師也已協助安排照護計畫以利監控。', emphasis: false, sources: ['E4', 'K1'] },
      { text: '近期檢查如', emphasis: false, sources: [] },
      { text: '腎功能數值', emphasis: true, sources: ['L7', 'L24'] },
      { text: '與', emphasis: false, sources: [] },
      { text: '心肺狀態', emphasis: true, sources: ['L1', 'L16'] },
      { text: '，都作為醫師評估您整體健康進展的重要參考，請維持規律回診，讓專業醫療團隊協助您保持穩定。', emphasis: false, sources: ['E3', 'E10'] },
    ],
    investigations: [
      {
        label: '腎功能（eGFR）',
        kind: 'lab',
        direction: 'worsening',
        trend: 'eGFR 35 → 33 → 32 mL/min/1.73m²',
        interpretation: '腎功能數值逐漸下降，建議維持規律回診，請醫師繼續追蹤。',
        sources: ['L7', 'L24'],
      },
      {
        label: '貧血相關數值',
        kind: 'lab',
        direction: 'fluctuating',
        trend: '血色素 11.2–12.1 g/dL',
        interpretation: '數值偏低且有些波動，可在下次回診時請醫師一起說明。',
        sources: ['L9'],
      },
      {
        label: '胸部影像',
        kind: 'imaging',
        direction: 'single',
        trend: '單次最新結果：雙側肺部浸潤與肋膜積水',
        interpretation: '這是一次的檢查結果，還不能代表長期變化，請交由醫療團隊結合症狀說明。',
        sources: ['L1'],
      },
    ],
    medicationEducation: [
      {
        name: '青光眼眼藥水（派滴兒、必目寧等）',
        benefit: '這些眼藥水用於協助控制眼壓，幫助保護視神經與維持眼睛狀況。',
        attention: '請依眼科醫師指示點藥；若同時使用多種眼藥水，可請醫師或藥師再次確認點用順序與間隔。',
        sources: ['M3', 'M4', 'M5', 'M6'],
      },
      {
        name: '攝護腺相關藥物',
        benefit: '紀錄中的藥物可協助排尿更順暢，減少攝護腺問題對日常生活的影響。',
        attention: '若服藥後容易頭暈，起身時可以慢一些；症狀持續時可在回診時告訴醫師。',
        sources: ['M19', 'M39'],
      },
      {
        name: '甲狀腺素補充藥物',
        benefit: '這類藥物補充身體需要的甲狀腺素，協助維持代謝與日常精神體力。',
        attention: '請依醫囑固定方式使用；若服用時間或與其他藥物的間隔不確定，可詢問醫師或藥師。',
        sources: ['M15', 'M32'],
      },
      {
        name: '降尿酸藥物',
        benefit: '這類藥物協助控制尿酸，支持長期關節與腎臟照護。',
        attention: '規律依醫囑使用較能維持效果；若有不舒服或用藥疑問，請先和醫師或藥師討論。',
        sources: ['M16', 'M33'],
      },
    ],
    medicationReview: {
      regimen: [],
      changes: [],
      reconciliation: [],
    },
    problems: [
      { label: '慢性腎臟病', basis: '照護計畫及多次血液檢查', kind: 'careplan', sources: ['K1', 'K2', 'L7', 'L24'] },
      {
        label: '青光眼',
        basis: '多次門診紀錄與眼藥水調劑',
        kind: 'diagnosis',
        sources: ['E2', 'E7', 'M3', 'M4', 'M5', 'M6'],
      },
      { label: '良性攝護腺增生', basis: '門診紀錄與藥物調劑', kind: 'diagnosis', sources: ['E6', 'E12', 'M19', 'M39'] },
      {
        label: '胃部病變（含息肉與潰瘍）',
        basis: '多次門診紀錄與腸胃藥調劑',
        kind: 'diagnosis',
        sources: ['E5', 'E15', 'M7', 'M9', 'M10', 'M11'],
      },
      { label: '脂肪肝', basis: '腹部超音波檢查', kind: 'lab', sources: ['L30'] },
      { label: '腎結石', basis: '腹部超音波檢查', kind: 'lab', sources: ['L30'] },
      { label: '膽囊沉積物', basis: '腹部超音波檢查', kind: 'lab', sources: ['L30'] },
    ],
    decisions: [
      {
        text: '請於下次門診時與醫師確認目前的腎功能狀況（eGFR數值追蹤）。',
        urgency: 'medium',
        rationale: '近期的檢驗結果顯示腎功能指數有變化（如 eGFR 35→33→32），適合向主治醫師確認治療調整方向。',
        sources: ['L7', 'L24'],
      },
      {
        text: '請與眼科醫師討論目前的眼藥水使用計畫，確認各項眼藥點用順序。',
        urgency: 'low',
        rationale: '有多種眼藥水（如派滴兒、必目寧等）正在同時使用中。',
        sources: ['M3', 'M4', 'M5', 'M6'],
      },
    ],
    // Same significant milestones as the medical view (identical refs +
    // categories) — only the label wording is plainer. Never more/fewer/other
    // events than the clinician sees.
    timeline: [
      { ref: 'K1', label: '開始腎臟照護計畫', category: 'followup' },
      { ref: 'E21', label: '因新冠肺炎住院', category: 'encounter' },
      { ref: 'E20', label: '因肺炎住院', category: 'encounter' },
      { ref: 'E19', label: '因咳血住院檢查', category: 'encounter' },
      { ref: 'E16', label: '意識混亂就醫', category: 'diagnosis' },
      { ref: 'L30', label: '腹部超音波檢查', category: 'lab' },
      { ref: 'E3', label: '肺炎門診治療', category: 'diagnosis' },
    ],
  },
}

export const demoSafetyScanSnapshots: Record<Audience, SafetyScanResultInput> = {
  medical: {
    scannedCount: 40,
    alerts: [
      {
        severity: 'medium',
        title: '慢性腎臟病惡化與腎功能追蹤',
        detail: '病人肌酸酐數值為 1.93 mg/dL 且 eGFR 降至 32 mL/min/1.73m2，處於慢性腎臟病 stage 3b，需持續監測。',
        evidence: [
          'Creatinine (mg/dL): 1.93 (2026-06-02)',
          'Estimated GFR (mL/min/1.73m2): 32 (2026-06-02)',
        ],
        sources: ['L7'],
        category: 'renal',
        recommendation: '建議於腎臟科門診定期追蹤腎功能與蛋白尿情形。',
      },
      {
        severity: 'medium',
        title: '多重藥物交互作用與潛在藥物負擔',
        detail: '病人同時使用 Imipramine (三環抗憂鬱劑) 及 Harnalidge (α-blocker) 以及多種腸胃藥物，需留意低血壓與抗膽鹼負擔。',
        evidence: [
          'IMIMINE S.C. TABLETS 25MG',
          'Harnalidge OCAS prolonged release tablets 0.4 mg',
        ],
        sources: ['M18', 'M19'],
        category: 'other',
        recommendation: '建議評估藥物重整，特別是評估抗膽鹼藥物之必要性。',
      },
      {
        severity: 'low',
        title: '心電圖異常追蹤',
        detail: '心電圖顯示竇性心搏過緩、左軸偏移及陳舊性前中膈梗塞。',
        evidence: ['Sinus bradycardia', 'Left axis deviation', 'Anteroseptal infarct'],
        sources: ['L16', 'L17'],
        category: 'monitoring',
        recommendation: '建議由心臟內科醫師定期追蹤心電圖變化。',
      },
    ],
  },
  patient: {
    scannedCount: 105,
    alerts: [
      {
        severity: 'medium',
        title: '腎功能定期追蹤',
        detail: '最新的腎功能報告（肌酸酐 1.93 mg/dL，估計腎絲球過濾率 32 mL/min/1.73m²）顯示腎臟需要持續照護，建議定期向腎臟科醫師回診，並依照醫囑使用藥物。',
        evidence: [
          'Creatinine (mg/dL): 1.93 (2026-06-02)',
          'Estimated GFR (mL/min/1.73m2): 32 (2026-06-02)',
        ],
        sources: ['L7'],
        category: 'renal',
        recommendation: '請於腎臟科回診時諮詢，平時請多注意尿量變化與下肢是否水腫，並在用藥前告知醫師您的腎臟狀況。',
      },
      {
        severity: 'medium',
        title: '藥物重複檢視',
        detail: '您目前有幾種藥物由不同診所同時開立，例如「便通樂膜衣錠」在示範嘉恩醫院與長青醫院重複出現，建議下次就診時確認用藥頻率以避免用量過多。',
        evidence: ['M8: 2026-06-25, 示範嘉恩醫院', 'M30: 2026-06-02, 示範長青醫院'],
        sources: ['M8', 'M30'],
        category: 'duplicate',
        recommendation: '請將所有目前正在服用的藥物帶至下次門診，由您的醫師確認目前的用藥清單是否需要整合。',
      },
      {
        severity: 'low',
        title: '藥物用量小提醒',
        detail: '部分眼藥水與慢性病藥物的給藥期限即將於幾天內到期，若藥物即將用盡，請記得按時安排回診。',
        evidence: [
          '派滴兒點眼液 (1d left)',
          '必目寧眼藥水 (1d left)',
          '舒而坦眼藥水 (1d left)',
          '康舒目點眼液 (1d left)',
        ],
        sources: ['M3', 'M4', 'M5', 'M6'],
        category: 'monitoring',
        recommendation: '若感到不適或有任何藥物相關疑問，請於回診時向醫師討論，不要自行停藥或調整劑量。',
      },
    ],
  },
}
